design/Memory.md
Spotted some leftover references while browsing
=> Dfinity -> IC

src/mo_config/internal_error.ml
=> Compiler crash: Tell user to report on github, not forum

doc/modules/language-guide/pages/actors-async.adoc
=> Word typo in documentation

doc/modules/language-guide/pages/basic-concepts.adoc
=> Improve description of substitution semantics

doc/modules/language-guide/pages/motoko.adoc
This PR replaces forked PR #2627
=> [Doc] add reference to open source and repo

rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/heap.rs, rts/motoko-rts-tests/src/gc/utils.rs, rts/motoko-rts/src/types.rs
In #2573 (0f55c58) I omitted creating creating closure tables and
checking them after GC, implementing it now.
=> GC tests: start creating closure table

test/run-drun/actor-class-cycles.mo
=> More test grooming

src/codegen/compile.ml
=> Use compile_eq_const

default.nix
this breaks the run-time dependency from our tests via `ic-ref-run` to things like Haskell library files
and documentation, by extracting just the relevant executable from the haskell package build, and should
speed up builds an `nix-shell` by downloading less stuff.
=> nix: create dedicated ic-ref-run derivation

Changelog.md
includes ExperimentalStableMemory.mo in stealth mode
=> Releasing 0.6.9

rts/motoko-rts/src/types.rs
See the node added with this commit and
https://github.com/dfinity/motoko/pull/2761#issuecomment-920765586 for
the problem this solves.
=> Use repr(C) in RTS struct

rts/motoko-rts-tests/src/mark_stack.rs
Previously for the tags in mark stack tests we were using `value - 1`
where `value` is the value being pushed to the stack.
Using actual tags in these tests is more resilient to changes so we now
use actual tags in mark stack tests.
=> Use real tags in mark stack tests

doc/modules/language-guide/pages/basic-concepts.adoc
it cause the link can't be open (404 error)
=> add missing closed bracket

Changelog.md
=> Releasing 0.6.13

Changelog.md, default.nix, doc/modules/language-guide/pages/compiler-ref.adoc, src/codegen/compile.ml, src/exes/moc.ml, src/mo_config/flags.ml
=> Make copying GC the default again

test/run-drun/callback-trap-upgrade.mo, test/run-drun/ok/callback-trap-upgrade.drun-run.ok, test/run-drun/ok/callback-trap-upgrade.ic-ref-run.ok
sorry for shouting wolf in #2937. At least we get more tests out of
this.
=> Test case for upgrade-after-trap-in-callback

src/js/common.ml, src/js/moc_js.ml, test/test-moc.js
Tested in https://github.com/dfinity/motoko-playground/pull/91
=> add stable var checking and gcflag to moc.js

.mergify.yml
=> mergify: preëmptively fix the deprecation message

test/run-drun/multi-value.mo, test/run-drun/ok/multi-value.drun-run.ok, test/run-drun/ok/multi-value.ic-ref-run.ok
=> tests: Code that uses multi-value block results

design/WhitePaper.md
More of a draft of a braindump than a polished paper. I may make another pass tomorrow.
=> Evolution white paper

default.nix
=> Bump version of node used for tests

src/prelude/prim.mo, test/run/ok/principal.run-ir.ok, test/run/ok/principal.run-low.ok, test/run/ok/principal.run.ok, test/run/ok/principal.wasm-run.ok, test/run/principal.mo
It’s silly to have `Principal.toBlob()`, but not the other direction.
=> Add `Prim.principalOfBlob()`

doc/modules/language-guide/pages/language-manual.adoc
remove duplicate keyword "assert", and add "do" keyword
=> update the keywords.

default.nix, nix/default.nix, rts/README.md, test/ld/Makefile
And some collateral fixes too.
=> Bump rust nightly

src/codegen/compile.ml
=> compile.ml: Wrap cycle prim impls in `share_code`

rts/motoko-rts/src/text.rs, rts/motoko-rts/src/types.rs, src/codegen/compile.ml
This is mostly mechanical. The intention is to take out some of the patch pressure (and mental load) from #3149.
=> Preparations and  refactoring for #3149

Changelog.md
in preparation of upcoming 0.6.25
=> `Changelog.md` items

test/perf/ok/sha256.drun-run.ok, test/perf/sha256.mo, test/perf/sha256/Array.mo, test/perf/sha256/Buffer.mo, test/perf/sha256/Debug.mo, test/perf/sha256/Hash.mo, test/perf/sha256/Int.mo, test/perf/sha256/Iter.mo, test/perf/sha256/IterType.mo, test/perf/sha256/List.mo, test/perf/sha256/Nat.mo, test/perf/sha256/Nat32.mo, test/perf/sha256/Nat64.mo, test/perf/sha256/Nat8.mo, test/perf/sha256/Option.mo, test/perf/sha256/Order.mo, test/perf/sha256/Prelude.mo, test/perf/sha256/Result.mo, test/perf/sha256/SHA256.mo
this module is used in practice, I belive, and a good example for
numeric-heavy code involving fixed width nats, so maybe a good addition
to our test suite.
=> Perf test suite: Add Enzo’s SHA256 module

nix/default.nix, nix/drun.nix
to match https://github.com/dfinity/ic/blob/master/rust-toolchain.toml
=> nix: Build drun with rust 1.60

test/run-drun/call-raw-candid.mo, test/run-drun/ok/call-raw-candid.drun-run.ok, test/run-drun/ok/call-raw-candid.ic-ref-run.ok
=> test: test call-raw using to/from_candid

rts/motoko-rts/src/gc/mark_compact.rs, rts/motoko-rts/src/gc/mark_compact/mark_stack.rs, rts/motoko-rts/src/types.rs
breaking out some obvious tweaks, as these stand individually
=> chore: preparations for #3231

Changelog.md, doc/modules/language-guide/pages/stablememory.adoc, nix/sources.json
* bump next-moc
* changelog++
* doc
=> feat: expose `ExperimentalStableMemory.stableVarQuery`

doc/README.md
Tested in https://github.com/wackyleo459/test-motoko-interpreter/pull/1
=> Update doc for interpreter support for markdown

src/docs/extract.ml, src/exes/mo_doc.ml, src/ic/url_test.ml, src/idllib/arrange_idl.ml, src/ir_def/arrange_ir.ml, src/ir_def/rename.ml, src/ir_passes/tailcall.ml, src/lowering/desugar.ml, src/mo_def/arrange.ml, src/mo_types/arrange_type.ml, src/mo_types/expansive.ml, src/mo_types/productive.ml, src/mo_types/type.ml
=> Fix stray logging in `mo-doc` and other cleanups

test/run/2662.mo, test/run/circular.mo, test/run/circular/a.mo, test/run/circular/article.mo, test/run/circular/b.mo, test/run/circular/user.mo, test/run/ok/2662.tc.ok, test/run/ok/2662.tc.ret.ok, test/run/ok/circular.tc.ok, test/run/ok/circular.tc.ret.ok
=> Test circular modules

default.nix
=> fix report-site derivation

doc/md/language-manual.md
Document of object combination/extension describing typing and evaluation.
=> doc: describe typing and evaluation of record combination/extensions

doc/md/modules-and-imports.md
Reported by @timohanke in slack. Thanks for the nudge!
=> typofixes in explicit `import`

doc/docusaurus/src/theme/CodeBlock/hljs_run.js, doc/md/language-manual.md
This only affects the local preview - still need to update portal (or, better, share code between them).
=> chore: highlight new `with` keyword with hljs/ add to list of keyword in `doc`

README.md
Also adding a link to the IDE. Plus a lot of other things.
=> Mention the Playground in the `README.md`

Building.md
Added extra instructions for MacBook M1 installation
=> Update the building instructions

src/mo_types/type.ml
https://github.com/dfinity/motoko/pull/3463#discussion_r988304014
=> tweak: leftover comment from #3463

src/pipeline/pipeline.ml, src/viper/pretty.ml, src/viper/syntax.ml
Adds reverse (viper -> Motoko) source region mapping.
=> viper: src-loc mapping

src/pipeline/pipeline.ml, src/viper/pretty.ml
=> viper: cleanups

.github/workflows/update-hash.yml
for the nix hashes updater script
=> chore: pull `nixpkgs` from channel `nixos-22.05`

Changelog.md, src/mo_frontend/typing.ml
=> chore: refactor rejection of generic shared functions

Changelog.md, doc/docusaurus/static/load_moc.ts, doc/md/base/Buffer.md
=> chore: rebuild doc; update changelog in preparation for release 0.7.3

.github/workflows/release.yml
along the lines of https://github.com/dfinity/internet-identity/commit/b87727a012cb86e8d2fc46dce74b57d0342f0ced
=> chore: quote the GitHub output file

.mergify.yml
as suggested in https://github.com/dfinity/motoko/pull/3559#issuecomment-1308730139
=> chore: automatise `docusaurus/package-lock.json`

src/js/common.ml, src/js/moc_interpreter.ml, src/js/moc_js.ml, src/mo_def/arrange.ml, src/mo_types/type.ml
This PR merges #3455 into #3477 to enable recent QoL improvements in the VS Code extension (such as better type information and autocompletion).
=> viper: enable recent VS Code extension improvements

.github/workflows/test.yml
These started failing recently :-(
=> chore: bump `peter-evans/*-comment` GH actions

doc/md/base/Array.md
Suggestion for an example to provide alongside the diagram
=> docs: example for `Array.equal`

doc/md/language-manual.md
=> doc: fix for doc issue #3636 regaring await*

doc/md/compiler-ref.md, doc/md/examples/Reminder.mo, doc/md/heartbeats.md, doc/md/timers.md
Adds a few examples how the timer mechanisms can be used.
=> doc: timers

.github/workflows/release.yml
this is just a band-aid, waiting for the official release...
=> chore: actually fix the `%0A` substitution problem

Changelog.md, src/codegen/compile.ml, src/ir_def/construct.ml, src/ir_def/ir_effect.ml, src/ir_passes/async.ml, src/mo_frontend/effect.ml, src/mo_types/type.mli, src/prelude/internals.mo
=> chore: minor revisions to #3630 (throw on send failure)

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
C.f. in https://github.com/cachix/install-nix-action/blob/master/README.md#features the last bullet point under _Features_.
=> chore: simplify `nix` install in CI

doc/md/about-this-guide.md, doc/md/motoko-introduction.md, doc/md/upgrades.md
Fix broken links in new Internet Computer developer docs.
=> chore: update links

doc/md/about-this-guide.md, doc/md/motoko-introduction.md, doc/md/upgrades.md, test/run-drun/ser-many-nat.mo, test/run-drun/write-barrier-check.mo
Generational GC seems to schedule at somewhat different points in the tests and thus occasionally exceed the limit for certain tests (that were already close at the limit before). In debug mode, the generational GC performs extensive full-heap sanity checks.
=> Test `rustc` upgrade

doc/md/base/Buffer.md, doc/md/base/ExperimentalInternetComputer.md, doc/md/base/List.md, doc/md/base/Nat.md, doc/md/base/index.md
to make it easier to release 0.8.2
=> chore: update base docs

Changelog.md, src/codegen/compile.ml
Tweak on #3809 - more like first draft - don't grok why it uses less stack though. Only difference is prep for recursive calls that must make better use of the wasm stack.
=> experiment: slight variation of 

src/codegen/compile.ml, test/run-drun/destabilization-crash/destabilization-crash.mo
This incorporates some review feedback from #3793.
=> tweaks to `Stack.alloc_words`

Changelog.md
=> Releasing 0.8.3

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
This is an emergency bump due to https://github.com/cachix/install-nix-action/issues/161
=> bump `install-nix-action` to v20

src/codegen/compile.ml, test/run/issue3887.mo
=> Backend: `trap` PrimOP does not return

src/codegen/compile.ml
Extracted from #3896, just some nice clean-up worth having.
=> Refactor: Common up array indexing code

nix/sources.json
see #3737, as it has been failing recently
=> chore: reference a PR's branch that fixes Darwin

doc/md/about-this-guide.md
removed a line so the /portal repo can build
=> remove line

src/codegen/compile.ml, src/mo_values/prim.ml, src/prelude/prim.mo, test/run/text-compare.mo
=> Implement Prim.blobCompare

Changelog.md
=> chore: state the credits

default.nix, test/run/candid.mo
exercises the solution found in #4130
Resolves #4130.
=> test: extracting argument 0 as a tuple

test/drun-wrapper.sh
in vain attempt to make CI more deteriministic
c.f.:
https://dfinity.atlassian.net/browse/DFN-1269
=> experiment: increase EXTRA_BATCHES arg to drun

.github/workflows/test.yml, src/js/common.ml, src/js/moc_js.ml
so that we can collect usage about base library in playground.
=> expose print_deps in moc.js

Changelog.md
=> chore: fix motoko-base PR references in changelog

.github/workflows/test.yml
=> fix: typo in `workflows/test.yml`

design/WhitePaper.md
Addes a link to resolved suggestion, fixed a typo.
=> chore: update `design/WhitePaper.md`

Building.md
in preparation for the upcoming release
=> chore: bump minor version in `Building.md`

doc/md/base/List.md, doc/md/base/Option.md, doc/md/base/Trie.md, src/mo_frontend/typing.ml, src/pipeline/pipeline.ml
* to suppress unused identifiers in libs
* also, update base doc
=> bugfix: fix tracking of current package in `pipeline.ml`

doc/md/base/Region.md, doc/md/stable-regions.md
As per [this forum post](https://forum.dfinity.org/t/shrink-region-by-using-region-grow-region-0/29672), note that shrinking or reducing a Region size is currently not possible
=> docs: note that cannot reduce Region size

.mergify.yml
=> chore: fix mergify warnings

LICENSE
=> Complete LICENSE

Changelog.md, doc/md/base/OrderedMap.md, doc/md/base/OrderedSet.md, doc/md/base/RBTree.md, doc/md/base/index.md, nix/sources.json
to pull in new OrderedSet and OrderedMap implementations
=> chore: bump base and docs, changelog++

Changelog.md, doc/md/base/Float.md
* update docs
* update changelog
=> chore: Releasing 0.13.4

.github/repo_policies/BOT_APPROVED_FILES
See policy change https://dfinity.slack.com/archives/CH4CADCJX/p1733844276935979 and (more in-depth) https://docs.google.com/document/d/1B8QeCsyUPws3gQj76lX-wTBMPls4V6qYRrR8tPg8o1Q/edit?tab=t.0
=> chore: first cut of bot-modifiable files

Changelog.md
=> chore: update `Changelog.md`

doc/md/getting-started/quickstart.md, doc/md/writing-motoko/arguments.md
Needed for the Dev Docs Restructure portal PR to build
=> docs: fix links

doc/md/meet-motoko.md
This PR introduces the first draft of the Meet Motoko section. It aims to provide:
A brief overview of Motoko, highlighting its key design aspects.
Installation instructions, including setting up Motoko with dfx.
A guide to developer tools, such as the VS Code extension.
Links to example projects to help developers get started quickly.
I think a button asset to replace the [Yes] and [No] feedback links, would be good. I removed the hello world example and it's the first part of the fundamentals section. I did not include mo-server either. Other than that let me know what you think of this first draft. Also I just realise reading this over that DFINITY Developer Forum should be lowercase "developer forum".
=> docs: rewrite and restructure meet-motoko.md [DRAFT]

doc/md/fundamentals/1-basic-syntax/1-defining-an-actor.md, doc/md/fundamentals/1-basic-syntax/6-literals.md, doc/md/fundamentals/1-basic-syntax/8-functions.md, doc/md/fundamentals/2-types/1-primitive-types.md, doc/md/fundamentals/2-types/10-options-results.md, doc/md/fundamentals/2-types/12-advanced-types.md, doc/md/fundamentals/2-types/14-type-conversions.md, doc/md/fundamentals/2-types/4-tuples.md, doc/md/fundamentals/2-types/5-records.md, doc/md/fundamentals/2-types/8-immutable-arrays.md, doc/md/fundamentals/2-types/9-mutable-arrays.md, doc/md/fundamentals/3-declarations/1-variable-declarations.md, doc/md/fundamentals/3-declarations/2-function-declarations.md, doc/md/fundamentals/3-declarations/4-class-declarations.md, doc/md/fundamentals/3-declarations/6-expression-declarations.md, doc/md/fundamentals/8-modules-imports.md, doc/md/motoko-tooling/3-mo-doc.md
This PR implements the suggestions from the Motoko team.
=> Motoko team suggestions

Building.md
How to submit towards SDK for inclusion into `dfx`.
=> chore: update `Building.md` (how to announce the release towards SDK)

.github/workflows/release.yml, .github/workflows/test.yml
=> chore: use `cachix watch-exec`

src/docs/adoc.ml, src/docs/extract.ml, src/docs/html.ml, src/docs/plain.ml
I didn't think the refactor was that big a change, and looks like we actually get to delete a few lines of code. WDYT?
=> mo-doc: Introduces a sum type for function args

README.md
=> chore: fixed broken link

.github/actions/test-blueprint/action.yml
Adds back the disk cleaning action such that the CI doesn't fail with out of disk space.
=> chore: add disk cleaning action

doc/md/fundamentals/2-types/14-subtyping.md
@jessiemongeon1 I did a fairly extensive rewrite of subtyping. Hope it's an improvement.
All examples were checked in make preview, then changed to no-repl and _include.
=> doc: rework section on subtyping

Building.md
- Grouped multiple commands into one for quick release instructions
- Added table of contents for quickly jumping to the desired section
TODO:
=> chore: improve release instructions

doc/md/base/Text.md
Result of running `make -C doc base`
=> chore: update docs

doc/md/fundamentals/5-control-flow/1-basic-control-flow.md, doc/md/fundamentals/5-control-flow/2-loops.md, doc/md/fundamentals/5-control-flow/5-switch.md, doc/md/fundamentals/9-error-handling.md
Builds on #5322 simplifying some examples and adding future todos (not now)
=> doc: misc-docs follow on

doc/md/12-base-core-migration.md
From PRs:
* https://github.com/dfinity/motoko-core/pull/346
* https://github.com/dfinity/motoko-core/pull/351
=> doc: add new `core` functions to migration guide

test/run-drun/non-par.mo, test/run-drun/ok/non-par.drun-run.ok
see https://github.com/dfinity/motoko/issues/5275#issuecomment-2990277240
this was a pilot error :-(
A minor, but confusing one...
=> chore: fix test

nix/pocket-ic.nix, test-runner/Cargo.toml
Fixes: https://github.com/dfinity/motoko/issues/5433
=> fix: fix pocket-ic testing in the darwin x86 CI

src/docs/extract.ml, src/lowering/desugar.ml, src/mo_def/compUnit.ml, src/mo_def/syntax.ml, src/mo_frontend/typing.ml, src/mo_idl/mo_to_idl.ml, src/mo_interpreter/interpret.ml, src/pipeline/pipeline.ml
=> experiment: remove redundant `FileU` compilation unit
