dfinity/motoko

.github/workflows/niv-updater-rare.yml, .github/workflows/niv-updater-trial.yml, .github/workflows/niv-updater.yml
The action didn't pull niv from the cache and wasted many GitHub Actions
minutes building niv. We use our fork where the issue is fixed until
knl/niv-updater-action#46 is merged.
This also sets a timeout of 2mn.
Thanks to @nmattia for noticing and fixing.
=> niv-updater-action: Make sure it finishes in time

doc/modules/language-guide/pages/about-this-guide.adoc
=> Clarify non-goals

.github/workflows/release.yml, Changelog.md, default.nix, release-files.nix, src/codegen/die.ml, src/exes/deser.ml, src/exes/didc.ml, src/exes/moc.ml, src/mo_config/internal_error.ml, src/source_id/.gitignore, src/source_id/gen.sh, src/source_id/generated.mli, src/source_id/source_id.ml, src/source_id/source_id.mli, test/repl/ok/double-import.stdout.ok, test/repl/ok/file-and-repl.stdout.ok, test/repl/ok/outrange-int-nat.stdout.ok, test/repl/ok/pretty-val.stdout.ok, test/repl/ok/stateful.stdout.ok, test/repl/ok/triangle-import.stdout.ok, test/repl/ok/type-lub-repl.stdout.ok, test/repl/ok/variant-shorthand.stdout.ok, test/run.sh
this way we’ll get something like
```
$ moc --version
Motoko compiler 0.1 (source cq98vl2b-xnb74m6b-2k3959b5-7jjskw5s)
```
I still want to include the source id, as a safe guard against two
builds for the same version floating around.
This means that the create-release-on-tag job will have to rebuild. I am
_not_ running the tests there, hoping that they won’t break if one
changes the banner…
Only release builds will have a version numbers. Builds of arbitrary
revisions will print what the do now, and executables built in the nix
shell will continue to report the `git describe` output, as of now.
This also fixes an embarrassing but that was actually deploying linux binaries in `motoko-macos-0.1.tar.gz`, which means the previous release was kinda broken. We should do another release once …
=> Release build: embed actual version number

rts/Makefile
This fixes tracking of .rs files in subdirectories by the RTS Makefile.
Previously a file in e.g. `motoko-rts/src/my_dir` would not be tracked, only
the ones at the top-level `motoko-rts/src` would be tracked. With this patch it
now recursively tracks all .rs files.
=> RTS makefile: Track .rs files in subdirectories

rts/motoko-rts/src/gc/mark_compact.rs
This fixes a bug when an object refers to itself. If we thread the
fields first, by the time we get the object's size the header will be
gone. So we need to get the size first, then thread the fields.
Bug caught by #2573 and a test will be added with that PR.
=> Compacting GC: get object size before threading fields

.github/workflows/test.yml
This version should include https://github.com/NixOS/nix/pull/3564 and
allow us to increase max-jobs. See #2621 for the previous attempt,
reverted in 8365e739f.
The install URL is obtained from https://github.com/NixOS/nix/runs/2895674848 (https://github.com/NixOS/nix/commit/323e5450a1a6e4eb97ba1c9aeba195187cfaff37)
=> GH CI: update nix, increase max-jobs

rts/motoko-rts-tests/src/leb128.rs, rts/motoko-rts/src/leb128.rs
Fixes #2625
Refactors decode functions to allow checking overflows.
New tests added for checking edge cases + overflows.
=> Fix sleb128_decode overflow checking

rts/motoko-rts/src/alloc/gc.rs
Originally discussed here: https://github.com/dfinity/motoko/pull/2573#discussion_r660366802
Previously grow_memory would allocate one more page than necessary when
the argument is a multiple of Wasm page size. New calculation fixes
that. The code is basically
(ptr + WASM_PAGE_SIZE - 1) / WASM_PAGE_SIZE
I.e. divide argument by WASM_PAGE_SIZE, round up. However we do this in
u64 to avoid overflows in `ptr` is larger than `u32::MAX -
WASM_PAGE_SIZE + 1`
Also moves `total_pages - current_pages` to the slow path to improve
performance slightly.
CanCan backend benchmark reports 0.002% increase in cycles.
=> RTS: fix pages calculation in grow_memory

rts/motoko-rts/src/closure_table.rs, rts/motoko-rts/src/gc/mark_compact.rs
Accidental renaming was done in #2573 while renaming the "Heap" trait to
"Memory" and "heap" identifiers to "mem".
=> Fix a typo and accidental renaming

design/DFX-Interface.md
Made metavariables more obvious, fixed typos
=> Minor formatting changes to DFX-Interface.md

doc/modules/language-guide/pages/compiler-ref.adoc, doc/modules/language-guide/pages/language-manual.adoc, src/exes/didc.ml, src/exes/mo_doc.ml, src/exes/mo_ide.ml, src/exes/mo_ld.ml, src/exes/moc.ml, src/mo_config/args.ml
* fix formatting of lots of broken operators (asciidoc gaslighting)
* remove defunct avoidance clause on block typing; 
* fix formatting of function arrows.
* mardown italics -> asciidoc italics
* add links to base for each prim type
* minor changes here and there
* indent some bnf to avoid scrollbars
* document new compiler options/regularlize description (we should really hide most of them)
I think the rich ASCII doc diff is too large for GH to handle, so many read 
https://hydra.dfinity.systems/build/5455225/download/1/docs/language-guide/language-manual.html
side by side with this.
Or just approve it.
=> Update and improve doc

rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/mark_stack.rs, rts/motoko-rts/src/gc/copying.rs, rts/motoko-rts/src/gc/mark_compact.rs, rts/motoko-rts/src/gc/mark_compact/mark_stack.rs, rts/motoko-rts/src/visitor.rs
This PR implements the mark-compact GC algorithm briefly described by
"High-Performance Garbage Collection for Memory-Constrained Environments"
section 5.1.2 (I think the original paper is "An Efficient Garbage Compaction
Algorithm" but that paper is a bit difficult to follow).
The idea is as follows: when marking an object we thread backwards pointers of
that object. After we linearly scan the heap as before. For a live object, we
unthread it and update backwards pointers to it to the objects new location,
move the object, and then thread its forwards pointers. After the pass all
objects are moved and all references are updated.
This reduces number of passes in the original mark-compact collector to 2.
CanCan backend benchmark reports -19.8% in instructions. Compared to copying
GC, …
=>  Compacting GC: thread backwards pointers in marking

.github/workflows/niv-updater-rare.yml, .github/workflows/niv-updater-trial.yml, .github/workflows/niv-updater.yml
Now that knl/niv-updater-action#46 is merged, use the official upstream repo.
The same change works in dfinity/sdk#1747.
=> Use upstream `niv-updater-action` again

rts/motoko-rts/src/idl.rs
Updated error message of empty input to be more explanatory per discussion below:
https://forum.dfinity.org/t/canister-xxx-trapped-explicitly-idl-error-empty-input/6002
=> Updated error message for empty input

rts/motoko-rts/src/idl.rs, test/run-drun/ok/issue-1847.drun-run.ok, test/run-drun/ok/issue-1847.ic-ref-run.ok
Updated error message of empty input to be more explanatory per discussion below:
https://forum.dfinity.org/t/canister-xxx-trapped-explicitly-idl-error-empty-input/6002
=> Updated error message for empty input (#2665)

src/codegen/compile.ml
=> Use `compile_exp_vanilla` where appropriate

rts/motoko-rts/src/types.rs
This adds debug assertions that no access outside of `Array`'s length is attempted.
=> Bounds-check `Array` access for the debug runtime

rts/motoko-rts-tests/src/mark_stack.rs, rts/motoko-rts/src/gc/mark_compact/mark_stack.rs, rts/motoko-rts/src/types.rs
When growing mark stack we should update `STACK_TOP` otherwise subsequent
pushes will think that the stack is full and call `grow_stack` again.
Discovered while debugging strange allocation pattern in #2650 with the
compacting GC. It turns out once the mark stack is full ever subsequent push
(until stack is smaller than the initial size again) doubles the stack size,
causing redundant allocations.
Regression test added.
=> Mark-compact GC: update STACK_TOP when growing mark stack

src/codegen/compile.ml
I suspect this will also resolve potential problems with trapping on 32-bit compilation platforms. I don't think it is related to #2671, but who knows?
=> Use `int32_of_big_int` when computing bignum limbs

src/codegen/compile.ml
Since `NumType.of_int` returns an `int`, this has not enough precision (just 31 bits) when
the compiler is 32-bit, e.g. on JS (Motoko Playground)
This patch switches to using `Big_int` instead.
Fixes #2671.
=> Guard against Motoko 32 bit values overflowing the compiler's 31-bit arithmetic

src/codegen/compile.ml
=> Serialisation: use purpose-built subroutines

Changelog.md, rts/motoko-rts/src/gc.rs, rts/motoko-rts/src/gc/copying.rs, rts/motoko-rts/src/gc/mark_compact.rs, rts/motoko-rts/src/memory/ic.rs, src/codegen/compile.ml, src/exes/moc.ml, src/mo_config/flags.ml, test/run.sh
We now avoid doing GC after every message and only do when
- Heap grows more than HEAP_GROWTH_FACTOR since last GC (1) and more than
SMALL_HEAP_DELTA is allocated since last GC (2)
or
- Current heap size is more than MAX_HEAP_FOR_GC (3)
(1) is to make sure we don't do GC when heap size does not change much. On
small heaps `heap_size * HEAP_GROWING_FACTOR` will be a small amount, so (2) is
to avoid doing redundant GCs in such cases. (3) is to make sure we'll have
allocation space for the next message when heap is larger than MAX_HEAP_FOR_GC.
(Thanks to @ulan for the algorithm)
New moc flag `--force-gc` added to do GC after every update message in tests.
New scheduling is enabled by default.
Using CanCan backend benchmark
With the current parameters (HEAP_GROWING_FACTOR, SMALL_HEAP_DELTA, …
=> Smarter GC scheduling

rts/motoko-rts/src/debug.rs, rts/motoko-rts/src/principal_id.rs, rts/motoko-rts/src/types.rs, rts/motoko-rts/src/visitor.rs, src/codegen/compile.ml
Two new objects OneWordFiller and FreeSpace introduced to mark unused
spaces in heap.
These are mainly needed in #2706 and for new gc experiments, but they
are also useful to mark the slop when shrinking blobs in principal id
functions.
Previously when shrinking a blob we were filling the unused space with
zeros, and the gc was skipping the zeros when scanning the heap for e.g.
debug prints or sanity checks.
With OneWordFiller and FreeSpace, for 1 and 2 words unused space we do
the same amount of writes (header or header + length), for anything
larger we do 2 writes, instead of one write per word.
=> RTS: Introduce heap objects for unused space

src/Makefile
since #2587, the generated file is `source_id/generated.ml`, and no
longer `source_id/source_id.ml`. The latter is a normal file that `make
clean` should not delete. So let’s tell `make` about this.
(It seems that either nobody runs `make clean`, or everybody expects
weird behaviour and isn’t surprised that `make clean` deletes committed
files.)
=> src/Makefile: Create/delete source_id/generated.ml

default.nix
so that ./bin/candid-tests is used and incremental development is
possible, just as for the other binaries built “by us” (`moc` etc.)
=> nix-shell: Do not include nix-built candid-tests

src/lib/lib.ml, test/run/issue2714.mo
it was possible that the thunk passed to `lazy_value` would itself
fulfil the promise, which led to an exception in some cases.
Assuming the function to `lazy_value` always produces the same value, we
can avoid that by simply not raising an exception here.
This fixes #2714.
=> Make Promise.lazy_value more forgiving

default.nix, rts/motoko-rts-tests/Cargo.lock, rts/motoko-rts-tests/Cargo.toml, rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/heap.rs, rts/motoko-rts-tests/src/main.rs
By default Rust's HashMap and HashSet hashers are non-deterministic,
which is a problem when debugging as the tests can fail differently in
consecutive runs. I even observed that a buggy test passes when I run
the test suite repeatedly a few times.
This PR switches to `fxhash`s HashMap and HashSet, which is just std map
and set with a deterministic hasher. In the future we should be careful
to not use std maps and sets and always use fxhash.
`maplit` is removed as the `hashmap` and `hashset` macros only allow
generating std maps and sets with non-det hashers.
=> Use deterministic hashers in RTS test suite

rts/motoko-rts/.vim/coc-settings.json
Feature "gc" is now gone, use "ic" to check all modules
=> Update IDE config for rts

rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/heap.rs, rts/motoko-rts/src/gc/mark_compact.rs
One line fix to thread self references during marking in mark-compact GC.
We had a test with self references but it accidentally passed. The problem was
none of the objects below the object with self reference were dead, so the
object was not moved, and as a result the field with the self reference had the
correct value even though we didn't update it.
The test is updated to add a dead object before the object with self ref. It
fails without the fix.
Test code is also updated to use a vector for the heap description, instead of
a map. This allows specifying object order in heap. With the previous HashMap
based implementation there is no way to reason about the object orders, so for
example the test with a backward pointer might or might not have a backward
pointer, depending on the …
=> Fix handling of self references in mark-compact GC, imrpove tests

src/codegen/compile.ml, src/codegen/instrList.ml
Pick up an idea to reduce the computational complexity of the loop searching for the field hash:
- don't use multiplication, use addition instead
- trust the type system that the hash is present, and scrap the termination check
This gives us a nice 0.5% reduction in benchmarks for cycles usage as well as shaving off the 0.1% size increase that we suffered with #2708.
------------------
this gives us a comparison in binary size for 65 calls:
```
[nix-shell:~/motoko]$ wasm2wat qr-sharemoc.wasm | grep obj_idx | grep 'call ' | wc -l
65
```
there is a single `func $obj_idx`
```
[nix-shell:~/motoko]$ ls -l *moc.wasm
-rw-r--r-- 1 ggreif staff 257898 Aug 13 12:19 qr-oldmoc.wasm <<< previous `master`
-rw-r--r-- 1 ggreif staff 258162 Aug 13 12:19 qr-newmoc.wasm <<< current `master`
-rw-r--r-- 1 …
```
=> Improve on #2708 by applying strength reduction and abolishing termination checks

test/run/idx.mo
This is a follow-on to #2708, addressing a [review comment](https://github.com/dfinity/motoko/pull/2708#discussion_r686132804).
The resulting Wasm is as expected:
``` wasm
(func $absurdities (type 8) (param $clos i32) (param $inp i32)
local.get $inp
i32.const 2
call $B_eq
if  ;; label = @1
loop  ;; label = @2
br 0 (;@2;)
end
unreachable
end
...
```
the rest is analogous.
=> Add tests to check for compilation of bottom (as object)

rts/motoko-rts/src/blob_iter.rs, rts/motoko-rts/src/continuation_table.rs
Shifting by one is enough to make a scalar value.
This was omitted in 365b4b8d471b14c18e5c525c757ec7135c1bc171
=> RTS: Shift scalar values by one instead of two

perf-delta.nix
this makes it easier to see if it actually has updated yet, and may
avoid confusion about what te base commit it.
=> CI: Include revisions in perf change comment

.github/workflows/test.yml
before, the `nix-build` step would build or download everything defined in the
`default.nix` file. But there is no point in downloading stuff from the
cache here; if it is there, all is well.
The [`nix-build-uncached` tool](https://github.com/Mic92/nix-build-uncached) supposedly fixes that. So let’s try.
=> CI: Use nix-build-uncached to speed up CI jobs

src/codegen/compile.ml, src/linking/linkModule.ml, src/wasm-exts/customModule.ml, src/wasm-exts/customModuleDecode.ml
- Implement extended name section
(https://github.com/WebAssembly/extended-name-section/blob/master/proposals/extended-name-section/Overview.md)
- Handle `start` functions in the RTS module in linker
These changes are needed to update to LLVM 12: #2542
=> Update linker in prep for updating LLVM

release-files.nix
This might resolve the glitch that threw the last release from the rails: https://github.com/dfinity/motoko/pull/2765#issuecomment-913717691
There was no receive-side match for the argument `internal`, thus the nix call failed.
=> Remove unnecessary attribute passing in release expression

src/codegen/compile.ml, src/mo_values/prim.ml, src/prelude/prim.mo, test/run-drun/explicit-trap.mo, test/run-drun/ok/explicit-trap.drun-run.ok, test/run-drun/ok/explicit-trap.ic-ref-run.ok, test/run-drun/ok/explicit-trap.run-ir.ok, test/run-drun/ok/explicit-trap.run-low.ok, test/run-drun/ok/explicit-trap.run.ok
the System API provides canisters with a way to explicitly trap with an
error message. This is very useful for developing, e.g. to get useful
messages in code you think is unreachable, or when checking invariants.
This exposes this as `Prim.trap`. Later this can be exposed in
`motoko-base` via `Debug.trap` maybe, and also the odd `Prelude.nyi`,
`Prelude.xxx` and `Prelude.unreachable` can be implemented that way in a
more helpful way.
Semantically this is like the existing `assert false`, just with better
control over the error message and a more helpful type (return type
`None`).
=> Prim.trap: Expose ic0.trap

Changelog.md, nix/sources.json
* bumps next-moc to expose Debug.trap and ExperimentalStableMemory
* remove StableMemory from changelog (for now)
=> update next-moc; hide StableMemory from changelog

src/codegen/compile.ml
- Rename tag_field -> variant_tag_field, to make it clear that this is
not the object tag but the variant tag.
- Typo fix: "top of the stacks" -> "top of the stack"
Co-authored-by: Gabor Greif <gabor@dfinity.org>
=> Minor refactoring in variant tags in the backend

rts/motoko-rts/src/gc/mark_compact.rs, rts/motoko-rts/src/types.rs, src/codegen/compile.ml
In compacting GC we need to distinguish a heap location (object or field
address) from object headers. Currently this is done by checking if the value
is smaller than or equal to the largest tag. Because first 64 KiB of the heap
is for Rust stack, as long as the largest tag is smaller than 65,536, we can
assume that values smaller than 65,536 are headers.
This way of checking if a value is a header or an address causes problems when
we want to use rest of the object headers to store more information. Examples:
- In #2706 we will use one bit in the header to mark large objects. At least
initially, we won't be compacting large objects, so mark-compact GC won't see
large objects and so won't have to care about large header values. But we may
want to do compaction on large objects, or store …
=> Set the lowest bit in object tags

rts/motoko-rts/src/memory.rs
No need to use bitwise tricks and then document, simple code compiles to
the same, efficient Wasm.
=> Refactor alloc_array size check

rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/heap.rs, rts/motoko-rts-tests/src/main.rs, rts/motoko-rts-tests/src/memory.rs, rts/motoko-rts/src/bigint.rs, rts/motoko-rts/src/debug.rs, rts/motoko-rts/src/gc/copying.rs, rts/motoko-rts/src/gc/mark_compact.rs, rts/motoko-rts/src/gc/mark_compact/bitmap.rs, rts/motoko-rts/src/gc/mark_compact/mark_stack.rs, rts/motoko-rts/src/mem_utils.rs, rts/motoko-rts/src/memory/ic.rs, rts/motoko-rts/src/principal_id.rs, rts/motoko-rts/src/text.rs, rts/motoko-rts/src/text_iter.rs, rts/motoko-rts/src/types.rs
Ascriptions can be lossy, so every usage of `as` can potentially cause
problems as we refactor the code.
So in this PR we reduce the usage of `as`:
- For `Bytes` and `Words` values, instead of `x.0 as usize` we now use
`x.as_usize()`. `usize` has the same size as `u32` on Wasm (which is
the only target we support), so `as_usize()` method uses `as` without
any checks in debug mode.
- For casting `u32` to `u64`, use `u64::from(x)`. `from` methods cannot
fail, and for numeric types they are only implemented for casting a
smaller type to a larger type.
- To aid readbility this PR also introduces `Words::as_u32` and
`Bytes::u32` and uses these methods instead of accessing the unnamed
field of `Words` and `Bytes`.
- Also remove a redundant unwrapping/wrapping of `Bytes` value when
dividing it …
=> Refactor ascriptions (`as`) in RTS, avoid accessing Bytes/Words fields

src/codegen/compile.ml, test/run-drun/assert.mo, test/run-drun/assert/Lib.mo, test/run-drun/ok/assert.diff-ir.ok, test/run-drun/ok/assert.diff-low.ok, test/run-drun/ok/assert.drun-run.ok, test/run-drun/ok/assert.ic-ref-run.ok, test/run-drun/ok/assert.run-ir.ok, test/run-drun/ok/assert.run-low.ok, test/run-drun/ok/assert.run.ok, test/run-drun/ok/live-upgrade.ic-ref-run.ok
Our builds are not reproducible because the filepaths reported in assert messages are build environment dependent.
A simple fix is to only report the basename of the file in the assertion message, though this loses some information and may be ambiguous if a  project imports two distinct files with the same basename (this is possible, but not that likely, given the current scale of motoko projects.)
A better approach my be to relativize the source file to the current main file or package, but this probably requires pervasive changes to our Source.ml region representation, or other measures, like storing the root dir in the compilation unit.
TODO:
=> Reproducibility: Make assertion error messages reproducible

.mergify.yml
mergify has deprecated the `strict: smart` method, and wants explicit
queues set up, as per https://blog.mergify.io/strict-mode-deprecation/
=> Mergify: Update configuration

.github/workflows/niv-updater-rare.yml, .github/workflows/niv-updater.yml, nix/default.nix, nix/sources.json
it is up to date enough these days, so a good chance to simplify the
setup.
=> Nix shell: Use niv from nixpkgs

.github/workflows/test.yml
This job cannot be run on forks without sharing secrets with forks, see
the note in [1] and #2864. To unblock PRs from forks this commit
disables "creates performance comment" job on forks. For now, for PRs
that can effect performance, we can run the job and post the results
manually.
[1]: https://github.com/peter-evans/create-or-update-comment#action-inputs
=> Disable "crate performance comment" job on forks

rts/motoko-rts/src/gc.rs
This reverts commit c9d4d0863dd5593a3b2c8ebff1e6a00e6854b59c.
See https://github.com/dfinity/motoko/pull/2848#issuecomment-956238678
=> Revert "Bump up MAX_HP_FOR_GC from 1GB to 3GB (#2848)"

.github/workflows/release.yml, .github/workflows/test.yml
the `install-nix-action` has picked up the new nix-2.4 version, and that
needs a configuration item to enable the new `nix` CLI used by
`nix-build-uncached`.
=> CI: fix nix options

default.nix, rts/motoko-rts-tests/Cargo.lock, rts/motoko-rts-tests/Cargo.toml, rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/random.rs
This implements a very simple random heap generation that caught a lot of bugs
in #2706. The idea is similar to QuickCheck/proptest style property testing: we
generate random heaps using a pseudo-random number generator and a fixed seed,
and then run the GC tests as usual (run both collectors, check GC properties).
Difference from QuickCheck/proptest-style testing is we don't implement
shrinking. Implementing shrinking manually is not a lot of work, but I believe
it won't work in practice, because checking subsets of the nodes/edges of the
graph will take exponential time (N nodes will have 2^N subsets of nodes), and
we really need to check all subsets as these graphs won't have any properties
that allows us to shrink more efficiently.
=> Backport random heap tests from osa1/page_alloc

default.nix, rts/motoko-rts/src/constants.rs, rts/motoko-rts/src/gc.rs, rts/motoko-rts/src/gc/copying.rs, rts/motoko-rts/src/gc/mark_compact.rs, src/codegen/compile.ml, src/exes/moc.ml, src/mo_config/flags.ml
This PR makes mark-compact the default GC strategy and improves GC scheduling.
New flag `--copying-gc` added to enable copying GC. `--compacting-gc` is now
enabled by default.
Mark-compact GC uses more cycles than copying GC (see below), but in return it
almost halves dirtied pages, and allows us to use a more efficient GC scheduler
as it works with less scratch space. When both of these are taken into account,
it becomes clear that mark-compact GC is much more efficient than copying GC,
and should be the default.
Furthermore, when used with the mark-compact collector, a new GC scheduler
makes it possible for the tested canister to run same number of calls without
getting stuck, while doing less GC.
**Comparing GC cycles and dirtied pages**: We run an old [CanCan backend][1]
canister, …
=> Make mark-compact the default collector, improve scheduling

test/run/optimise-for-array.mo
Maybe later we'll have some compression here and better have a regression test in place, just in case...
=> Make sure that one-byte element optimised iteration still works

src/codegen/compile.ml
... by doing a pointer comparison first, and when not equal
proceed as usual (except when both are compact, the result
is `false`, as we already checked for identity).
Well, I conjecture that this helps, and the actual cycle counts w.r.t. our benchmarks indicate an improvement of 0.3%, so I guess this could go in.
The discussion happened in JIRA [IC-622], but the gist is captured in the PR.
=> Make bignum equality a bit more performant

.github/workflows/release.yml, .github/workflows/test.yml
Domen gave me the hint that the crashes tend to happen in `nix` GC,
see e.g. https://github.com/NixOS/nix/issues/4246
The GitHub release action for new tags keeps failing on MacOS X
=> Bump `install-nix-action` and disable GC for release action

doc/modules/language-guide/pages/control-flow.adoc
Corrects:
- type of the `upper` bound of `range` constructor function
- spelling of `revRange`
- types of the bounds of `revRange` constructor function
- return type of the `revRange` constructor function
fixes #2920
=> Fix documentation for `range` and `revRange`

src/lang_utils/error_codes.ml, src/mo_frontend/typing.ml, test/fail/ok/pat-inconsistent.tc.ok, test/fail/pat-inconsistent.mo
=> Catch error arising in `as_variant_sub` when scrutinee is not variant

src/codegen/compile.ml, src/ir_def/arrange_ir.ml, src/ir_def/check_ir.ml, src/ir_def/freevars.ml, src/ir_def/ir.ml, src/ir_def/rename.ml, src/ir_passes/async.ml, src/ir_passes/await.ml, src/ir_passes/const.ml, src/ir_passes/eq.ml, src/ir_passes/erase_typ_field.ml, src/ir_passes/show.ml, src/ir_passes/tailcall.ml, src/lowering/desugar.ml
The "upgrade" record is renamed to "system" so that it can fit more things unrelated to upgrades.
=> Rename upgrade record to system

default.nix
to enable `make -C src DUNE_OPTS=--watch moc`.
=> Add `nixpkgs.fswatch` to the nix shell

rts/motoko-rts/src/gc/mark_compact/bitmap.rs
I have rewritten the code which finds the next set bit in the marking bitmap (`BitmapIter::next`) to eliminate the inner `if`. This was suggested in #2952.
Branchless execution indeed gives nice wins in measured cycles:
```
[nix-shell:~/motoko]$ ghc -e "100-27424377/28288331*100"
3.0541002931562105
```
About 3% cycle reduction on GC-heavy code. More benchmarks in the PR.
=> Make bitmap scanning branchless

src/lowering/desugar.ml, test/run/issue2975.mo, test/run/issue2975/mod.mo
this fixes #2975.
In general, it is always fishy if the desugarer uses `@` to merge
different decls into one BlockE, unless there is a guarantee that the
bound names are disjoint. I won't be surprised if there are more bugs
like that lurking.
=> Fix scoping error in desugarer

nix/default.nix
This should speed up `nix-shell` etc. when we don't apply any patches,
without removing the code to do so.
=> `nix`: don't patch `nixpkgs` if we don't have patches

.github/workflows/update-hash.yml
The `release` branch  is also off-limits for hash updates.
=> Disable hash updates for `release` branch

.github/workflows/test.yml
`nix-2.4` has a (memory, Boehm) GC bug on macOS, this PR works around it.
See also #2913.
Also, for background, https://github.com/NixOS/nix/issues/4893.
=> Apply the macOS `nix-2.4` GC treatment

rts/motoko-rts/src/lib.rs
Redundant `#![feature(...)]`s generate warnings as we update rustc, so
no need to add a TODO about removing them.
=> RTS: remove a TODO

.github/workflows/test.yml, default.nix
we are now building them twice, but with caching, so only a problem if
they actually fail.
Also include tests.qc in the default test run. This reverts 41b4fbecc6c78996df146bf26cdda583a5c57ee. It’s against the principle of least surprise if `nix-build` does not build something that `nix-build -A tests` builds. If the QC test runs too long, we should make it run fast by default (few iterations) and maybe add a separate job (daily?) for a long run.
=> CI: Build tests with nix-build to show logs

.github/workflows/niv-updater-trial.yml, .github/workflows/niv-updater.yml
now that the replica devs are developing the replica in the open we get
to bump `ic` very often. Most changes are completely irrelevant to us,
but having a daily `niv ic` commit is noisy, and we don’t want to
download `drun` so often.
So let’s treat `ic` like `nixpkgs`: Every week (not day) a bot creats a
PR. If that is green then the new `drun` didn’t break anything. The PR
gets closed, but not merged, automatically. But we’d notice if it
breaks.
When we _do_ want to bump `ic`, we can do it manually, or reopen one of
those PRs.
=> CI: Update the ic bump more rarely

default.nix, nix/default.nix, rts/Makefile, rts/cargo-vendor-tools/Cargo.lock, rts/motoko-rts-macros/Cargo.lock, rts/motoko-rts-tests/Cargo.lock, rts/motoko-rts-tests/Cargo.toml, rts/motoko-rts/Cargo.lock, rts/motoko-rts/Cargo.toml, rts/motoko-rts/native/Cargo.lock, rts/motoko-rts/native/Cargo.toml
> [`rustc` v1.59.0 is now beta](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html), let's use it!
Well, the stable `rustc` (just like beta) doesn't support certain features yet, so we _really_ want a nightly.
We also update all rust-related dependencies to the most recent ones.
=> Switch `rustc` to a more fresh nightly

Changelog.md, doc/modules/language-guide/pages/compiler-ref.adoc, src/codegen/compile.ml, src/exes/moc.ml, src/wasm-exts/customModule.ml, src/wasm-exts/customModuleDecode.ml, src/wasm-exts/customModuleEncode.ml
* version is report as UTF8 release or, if unavailable, git revision, matching moc --version.
* section defaults to private.
=> feat: add `motoko:compiler` ICP custom section with version info

.github/workflows/test.yml, CI.md, default.nix
This publishes our various reports to https://dfinity.github.io/motoko/. So far, only for `master` (github action doesn’t support PR deployments like netlify would).
=> CI: Publish reports to Github Actions

src/codegen/compile.ml
this just moves a part of `compile_exp` into a helper function; no other
change.
=> Refactor compile.ml in preparation for #3159

src/codegen/compile.ml, src/wasm-exts/customModuleEncode.ml
This is a prelude to #3149. It doesn't change the generated code, just introduces a few holes in the serialiser that can be plugged with code fragments from a `Stream`. Later there will be different `Stream` implementations, but for now we only have the legacy `BumpStream` one. (Actually, there is a minor change in the generated code, which reflects how the stream now `reserve`s a small scratch area for writing, whereas previously it would write right away, and bump the pointer thereafter.)
**Big caveat**: The generated functions coming from `Serialization` (by `Func.share_code`) are still named the same. To make the naming sane, the `Stream` needs to bring its own name plumber. Since we only instantiate once in this PR, this is currently not a problem.
TODO: We definitely need two more …
=> Make module `Serialization` parametrised in the output streaming direction

src/codegen/compile.ml, test/run-drun/inline.mo, test/run-drun/ok/inline.drun-run.ok, test/run-drun/ok/inline.ic-ref-run.ok
Add a bug repro for #3159
```
//MOC-ENV MOC_UNLOCK_PRIM=yesplease
import Prim "mo:⛔";
actor {
func inline(t1: Text, t2 : Text) : Text = t1 # t2;
func makecalls() : () {
let t1 = inline("a","b"); // should be inlined
var p = ("c","d");
let t2 = inline p; // should not be inlined, but a still direct call
};
public func go() : async () {
makecalls();
}
}
//SKIP run
//SKIP run-ir
//SKIP run-low
//SKIP comp-ref
//CALL ingress go "DIDL\x00\x00"
```
generates 
```
(func $makecalls (type 4) (param $clos i32)
(local $t1 i32) (local $p i32) (local $t2 i32) (local $clos.1 i32)
i32.const 66431
i32.const 66419
call $text_concat
local.set $t1
i32.const 66403
local.set $p
i32.const 66367
local.tee $clos.1
local.get $p
call $from_2_tuple
global.get 2
global.get 3
local.get $clos.1
i32.load offset=5 …
```
=> bug: prim inliner produces unexpected indirect calls when call_as_prim is false.

src/codegen/instrList.ml, test/run/words.mo
Inspired by #3183. Fixes #3183.
- `push 0; i64.Eq` ~~> `i64.Eqz`
- `push n; i64.Eqz` ~~> `0` or `1` depending on `n`
- and the same for `i32.Eqz`
These rules are mostly triggered by the test suite, but I have added new tests too, so that all are covered.
=> Simple peephole rules around `Eqz`

rts/motoko-rts/src/bigint.rs, rts/motoko-rts/src/idl.rs, rts/motoko-rts/src/principal_id.rs, rts/motoko-rts/src/text.rs, rts/motoko-rts/src/text_iter.rs, rts/motoko-rts/src/types.rs
In most contexts `Blob` is being read from, so make `const` the default.
`as_blob_mut` is provided to allow write access.
=> rts: make `Blob` immutable by default

src/lib/lib.ml
this fixes #3212, and adds a few more tests.
=> Lib.FilePath.normalize: Make more robust

rts/motoko-rts/src/bigint.rs
Non-negatives have `sign == 0`, so using inequality. There are only two possibilities:
https://github.com/libtom/libtommath/blob/develop/mtest/mpi.h#L35
=> rts: micro-optimise `mp_isneg`

nix/sources.json
and switch to branch `main` so that auto-bumping works again.
=> Bump musl-wasi

Changelog.md, doc/README.md, doc/modules/language-guide/pages/language-manual.adoc, test/run-drun/call-raw-candid.mo, test/run-drun/ok/call-raw-candid.drun-run.ok, test/run-drun/ok/call-raw-candid.ic-ref-run.ok
Finishes off #3232 (which finished off #3155)
In language manual.adoc:
* add syntax
* document semantics
[ ] general, standalone page with simple examples?
=> doc: Candid serialization syntax

.gitignore
Ignores project config files and directories generated by VSCode, IntelliJ-based IDEs, Eclipse, Vim, etc. 
Adding as a PR since this tends to be a reasonably common practice for open-source repositories. These specific entries are from the `.gitignore` in [rust-lang/rust](https://github.com/rust-lang/rust/blob/master/.gitignore#L13-L23).
=> Add common editor config directories to .gitignore

doc/modules/language-guide/pages/language-manual.adoc
missed a few keywords... i use these in my code generators so wanted to make sure they're up to date
=> language-manual: more keywords

src/codegen/compile.ml, src/lowering/desugar.ml, src/mo_types/type.ml, src/mo_types/type.mli, src/prelude/internals.mo, src/prelude/prim.mo, test/fail/ok/illegal-await.tc.ok, test/run-drun/ok/query-footprint.ic-ref-run.ok, test/run-drun/query-footprint-overflow.mo, test/run-drun/query-footprint.mo
(cherry-picked commits from #3278 before things went south)
The current implementation of `stableVarInfo` is an asynchronous function that:
* has (first-order) type `(actor {}) -> async { size : Nat64 }` 
* is a local, async *update* function
* takes a redundant actor reference,
* takes two hops through the scheduler.
* doesn't reflect that it's essentially pure.
This refactoring, instead, provides a *higher-order* primitive that, when applied, returns an obviously pure *query*:
* has (higher-order) type `() -> (shared query () -> { size : Nat64 })` 
* is a local synchronous function, returning a *query*.
* avoiding the extraneous scheduling,
* simplifying the implementation,
* avoiding the need to pass the actor reference.
(The prim is higher-order only because we don't allow primitive …
=> feat: refactor `stableVarQuery` as prim returning an obviously pure (and more efficient) query

src/languageServer/definition.ml, test/lsp-int/Main.hs
I rewrote most of `definition_handler` to account for edge cases related to finding definitions in external files. 
- It's now possible to jump to the definition of an import identifier (rather than having to click on a qualified member name). For example, `import M|ap "HashMap"` (where `|` is the cursor) jumps to the top of `HashMap.mo` instead of doing nothing (fixes dfinity/vscode-motoko#17). 
- The new implementation also has a more permissive default behavior for missing declarations. In cases where the module path is known but the qualified symbol is unknown, the language server attempts to direct the user to the relevant module. This is mostly intended as a fallback for situations where the index is missing an expected declaration, such as when the other file has a syntax error. …
=> Improve support for navigating to definitions in external modules

Changelog.md, nix/sources.json
```
public func countInstructions(comp : () -> ()) : Nat64
```
Given computation, `comp`, counts the number of actual and (for IC system calls) notional WebAssembly instructions performed during the execution of `comp()`.
More precisely, returns the difference between the state of the IC instruction counter (_performance counter_0) before and after executing `comp()` (see [Performance Counter](https://internetcomputer.org/docs/current/references/ic-interface-spec/#system-api-performance-counter)).
NB: `countInstructions(comp)` will not account for any deferred garbage collection costs incurred by `comp()`.
=> feat: expose `ExperimentalInternetComputer.countInstructions(comp)`

src/codegen/compile.ml, test/run/array.mo, test/run/ok/array.tc.ok
Abolish `UnboxedBool` in favour of `Vanilla`. We now always use {`0`, `1`} for `Bool` values, since they never get dereferenced, and GC avoids visiting everything that is not in the dynamic heap (e.g. small constants, pointers into the first page etc.)
Resolves #2906.
=> Abolish `UnboxedBool` stack representation

src/mo_types/type.ml, test/fail/issue-3318.mo, test/fail/ok/issue-3318.tc.ok, test/fail/ok/issue-3318.tc.ret.ok
Our type pretty printer (the bane of my life) was suppressing arity differences between functions types. This fixes that by parenthesizing an argument/result sequence when it is a unary sequence containing a single tuple type.
Fixes issue #3318.
Let's hope it passes CI.
=> bugfix: improve pretty printing of function types to reflect arity differences (issue #3318)

design/WhitePaper.md
Some  omissions:
- https://github.com/dfinity/motoko/blob/master/design/WhitePaper.md#modules ought  to mention cyclic import legalisation
=> Typofixes in whitepaper

src/codegen/compile.ml, test/run/conversions.mo
see https://github.com/dfinity/motoko/pull/3330#discussion_r907673478
`"can_tag_i32"` is now one instruction shorter
`"box_i32"` is now keeping more values tagged and less go to the heap
TODO:
- write a hashing-heavy benchmark
=> Quicker test for `i32` taggability and more tagging opportunities

Changelog.md, src/codegen/compile.ml, src/mo_values/prim.ml, src/prelude/prim.mo, test/run-drun/empty-actor.mo, test/run-drun/ok/rts_gc_instructions.drun-run.ok, test/run-drun/rts_gc_instructions.mo
Instrument calls to the collector to record IC instruction count just before and after collection, reporting the first number as instructions due to mutator (computation) and the difference as the instructions due to GC (may be low when scheduled selectively).
Exposes two new prims:
* rts_mutator_instructions: () -> Nat
* rts_collector_instructions : () -> Nat
Both return the stats for the *previous* messages.
(NB. We can't obtain these numbers using the user-level performance_counter since that always excludes GC times).
Intended for internal benchmarking of GC.
=> feat: record instruction costs of mutator and collector

release-files.nix
This should fix the `release` action that failed the last time.
Verified that the result contains `...motoko-release-0.6.30/moc-0.6.30.js` and it looks like a minified `.js` file to me.
=> Only consider minimised `*.min.js` files for the tarball

doc/md/examples/grammar.txt, emacs/motoko-mode.el, src/mo_frontend/error_reporting.ml, src/mo_frontend/parser.mly, src/mo_frontend/printers.ml, src/mo_frontend/source_lexer.mll, src/mo_frontend/source_token.ml, test/fail/bad-obj-base.mo, test/fail/check-record.mo, test/fail/obj-empty-with.mo, test/fail/obj-with.mo, test/fail/ok/check-record.tc.ok, test/fail/ok/obj-empty-with.tc.ok, test/fail/ok/obj-empty-with.tc.ret.ok, test/repl/object-ext.sh, test/run-drun/obj-ext-await.mo, test/run/object-extend.mo, test/run/objects-order.mo
On top of #3367.
Introduces the `with` keyword for functional object extension.
Due to popular request this implements the `{ base and bases with field = value; ... }` syntax.
TODO:
- update GitHub syntax description (check `and` too!)
- update VSCode syntax description (https://github.com/dfinity/vscode-motoko/blob/master/syntaxes/Major.tmLanguage)
=> Introduce and use `with` keyword

src/exes/moc.ml, src/lang_utils/error_codes.ml, src/mo_config/flags.ml, src/mo_frontend/typing.ml, test/fail/object-ext-var-base.mo, test/fail/ok/M0172.tc.ok, test/fail/ok/M0173.tc.ok, test/fail/ok/M0175.tc.ok, test/fail/ok/object-ext-var-base.tc.ok, test/fail/ok/object-ext-var-base.tc.ret.ok, test/run/object-extend.mo
Make mutable field aliasing (when extending/merging records) an experimental opt-in feature, and hide it behind a feature flag. When the flag is not supplied, an error is emitted that instructs the user to overwrite all `var` fields from bases explicitly. When `--experimental-field-aliasing` is given no such error gets emitted, and the mutable cells of bases are aliased in the resulting record.
See discussion in #3084 why this is a necessity.
Also contains a few minor tweaks.
=> Make overwriting of `var` fields from bases obligatory

src/lowering/desugar.ml, test/run/object-extend.mo
Builds on #3084.
(The lowering phase also need to promote the type of bases, not just typing. Infer_exp_promote doesn't promote the annotation on the expression, so you need to do it  manually in lowering again).
Fixes #3405.
=> fix for #3405

samples/hoare.mo, samples/quicksort.mo, test/fail/ok/syntax7.tc.ok, test/fail/syntax7.mo, test/run/hoare.mo, test/run/quicksort.mo
Fix a small issue in the quicksort samples and test cases, such that it does not run in an endless loop in certain cases (e.g. in the presence of duplicates that are chosen as pivot).
=> fix a small issue in quicksort samples

doc/md/actor-classes.md
Fix a broken doc link found during preview of portal update PR
=> doc: fix broken link to anchor

README.md
- Adds @ByronBecker's Motoko library starter template to the "Community resources" section in the readme
- Removes the `node-motoko` status badge (since it uses a different versioning system)
=> Link Motoko library starter template in readme

.github/workflows/niv-updater-trial.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
This after I've nudging the thing endlessly and it always timed out on me...
For now this is only affecting the `trial` updates, but I've seen the others failing too.
=> bump timeout for `niv-updater-action` to 3 mins

.github/workflows/niv-updater-trial.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
Still waiting for releases w.r.t.
=> chore: fix CI deprecation warnings, bump to `node16`

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
This is an afterburner to #3482.
Alas, more warnings appeared:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore: bump `cachix-action` to v11 and `install-nix-action` to v18

src/js/common.ml, src/js/moc_js.ml
Adds a `Motoko.viper()` function in `moc.js` (used in https://github.com/dfinity/vscode-motoko/pull/78).
=> viper: `moc.js` endpoint for VS Code

.github/workflows/update-hash.yml
See the failure in #3509.
Looks like there is a new field:
=> chore: try fixing the NO-PULL problem in `update-hash`

Changelog.md
new release to avoid recently introduced bugs in base/Buffer.mo.
=> Releasing 0.7.2

src/viper/pretty.ml
Fixes a bug which causes the source map to remain the same in subsequent runs of `Pretty.prog_mapped` via `moc.js`.
=> viper: fix source locations for repeated code translations

Changelog.md, src/codegen/compile.ml, test/bench/ok/heap-32.drun-run.ok, test/run/array-gen.mo
* Eliminating unnecessary repeated array index bounds check while initializing an array.
* Faster iteration through new array on initialization by advancing an element pointer.
Applies to `Array.init` and `Array.tabulate`.
**More than 2x faster array initialization**
Measuring the number of mutator instructions with an array of 10_000_000 Nat elements. Tabulate uses `x -> x`.
Operation   | Unoptimized   | Optimized | Speedup
------------|---------------|-----------|-----------
`init`      | 260e6         | 120e6     | 2.17     
`tabulate`  | 380e6         | 280e6     | 1.36
Measuring the number of mutator instructions in GC benchmark. 
Benchmark Case      | Unoptimized   | Optimized | Speedup
--------------------|---------------|-----------|-----------
`blobs`             | 4.56e7 …
=> Performance Improvement: Array.init and Array.tabulate

.github/workflows/release.yml
Removes warnings as noted in
https://github.com/dfinity/motoko/pull/3483#issue-1406029328
resolved according to
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
_N.B._: we do not use `save-state`, so nothing to do on that front.
Also changes some convoluted shell substitutions to `perl`.
=> chore: remove use of `set-output` from CI

.github/workflows/update-hash.yml
The `NIV_UPDATER_TOKEN` is not up to the task pushing to the repo. Let's see if this gets better.
See: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
=> experimentally try using the GH-generated token

src/codegen/compile.ml
So far, the IC does not support wasm using multi-value returns from functions and blocks (see #1459). The backend was originally written with that feature in mind, and later we added a work-around (module `FakeMultiVal`).
For functions we work around it by storing multiple values in fixed globals, and reading them after the call. No allocations needed.
For blocks with multiple values, however, we allocate a tuple (array) on the heap, write the values there, and read them later. This adds unnecessary heap churn and fills up memory faster.
So this PR uses the mechanism from the functions also for blocks.
Goes well with #3556
Here is a (particularly bad) example:
In
```motoko
func multi_value_blocks(n : Nat) : (Nat, Nat) {
return (
if (n == 0) {
returns_tuple()
} else {
if (n == 1) { …
```
=> Multi-value emulation: Use globals, not allocated tuples

Building.md
M1 build should already be supported out of the box (see #3561). Testing still shows some failures (`wasmtime` problems?).
=> Building on the M1 works

default.nix
It still has somewhat outdated backends, but we never had problems with those.
But this gives a non-moving download URL, so that's a win!
=> viper: switch to stable server

src/languageServer/imports.ml, src/mo_frontend/assertions.mly, src/mo_frontend/parser.mly, src/mo_frontend/parser_lib.ml, src/mo_frontend/parsing.ml, src/mo_frontend/parsing.mli, src/pipeline/pipeline.ml, test/fail/ok/verification-asserts.tc.ok
Turns out I was doing a bunch of things wrong. Now we make the relevant `Lexer_lib.mode` accessible from the parser productions (previously it just accessed a constant thing).
This makes `--viper` to select the `verification` mode in the parser too (lexer was already fine).
=> fix: thread the mode into the parser

src/pipeline/pipeline.ml, src/prelude/internals.mo
This is a response to the review comment about better not use experimental features in production code.
Personally I am not sure this is an issue :-)
=> resort to one-element mutable arrays as a workaround for aliased `var` field

src/js/common.ml, src/mo_def/arrange.ml, test/test-moc.js
Makes it possible to extract and display Markdown doc comments in the VS Code extension and other JS environments.
=> feat: add doc comments to `moc.js` parse output

Changelog.md, src/codegen/compile.ml
Mainnet doesn't yet support DTS for `canister_heartbeat` yet, so a long GC may fail to complete when it would in an ordinary message supporting DTS.
This PR suppresses the GC call, leaving it to the already scheduled async message executing Motoko `system` function `heartbeat`, which will run with DTS enabled, avoiding the issue (and a potential space leak).
#3622 tracks the need to revert this hack once IC heartbeats support DTS.
=> hotfix: suppress GC in heartbeat

README.md
Context: https://forum.dfinity.org/t/mops-on-chain-package-manager-for-motoko/17275
=> chore: add MOPS to the readme under "Community resources"

README.md
Adds [Blocks](https://github.com/blocks-editor/blocks) to the community resource list as a response to various requests (e.g. [this recent forum post](https://forum.dfinity.org/t/in-defense-of-dom-and-the-dfinity-team-there-is-a-future-for-the-internet-computer/17241/)) for low-code canister builders in the IC.
=> Add Blocks Editor to the readme under "Community resources"

nix/default.nix
Recent `drun` builds require 1.65, so let's leapfrog!
=> chore: bump `rustc` stable to 1.66

.github/workflows/niv-updater-trial.yml
This is a test balloon for gaining experience with the `main` revision of the GH action. As soon this hits our `master` branch I can test it by triggering the action via nudging.
If it doesn't work, no biggie, the action will need another update.
_Context_: https://github.com/knl/niv-updater-action/issues/56
=> `niv-updater-action` bump (experiment)

test/run-drun/timer-cancel.mo
It seemed flaky with compacting-gc. Increased the initial timer's duration to 3 seconds.
=> fix flaky timer test

.github/workflows/release.yml
Unfortunately the last change was bogus (I almost expected it). So revert it.
Adds minor improvements and bumps `upload-release-action` to latest.
=> fix the release action

test/run-drun/ok/timer-cancel.drun-run.ok, test/run-drun/ok/timer-cancel.ic-ref-run.ok, test/run-drun/ok/timer-initial.drun-run.ok, test/run-drun/ok/timer-initial.ic-ref-run.ok, test/run-drun/timer-cancel.mo, test/run-drun/timer-initial.mo
This removes the textual outputs and relies on checking the globals instead.
=> chore: make timer tests more deterministic

.github/workflows/test.yml, .github/workflows/update-hash.yml
Restrict _dependabot_ from running on actions that need access token. The reason is that PRs initiated by dependabot don't have access to the `NIV_UPDATER_TOKEN` and thus cannot modify the repository, causing every build to fail twice:
- in the `update-hash` workflow
- in the performance diffing step of the `build` workflow when changing a PR comment.
This PR suppresses those mutations and as such the automatisms can bring the PR to completion.
For reference, a [recent failed CI run's log](https://github.com/dfinity/motoko/actions/runs/4025099722/jobs/6918617978).
=> Exclude updating nix hash for dependabot

.github/workflows/release.yml
This should fix the upload difficulties we had for a few days.
When there is an official release I'll bump again.
=> chore: bump `upload-release-action`

.github/workflows/release.yml
=> chore: the official label of `upload-release-action` now incorporates all fixes

.github/workflows/release.yml, .mergify.yml
For some strange reason #3762 exhibits a looping behaviour adding and removing the merge label. Stop it.
Fun fact: in #3559 the bot has tried >14000 times.
=> chore: stop `mergify` from looping

src/lowering/desugar.ml, src/prelude/internals.mo, test/fail/ok/illegal-await.tc.ok
optimizes #3758, exploiting async*/await* to remove a redundant yield on (default) class construction.
Also refactors code to be more understandable, now to we can abstract the installation code into helper in internals.mo, rather than generating lots of unreadable IR.
=> bugfix: follow on PR to #3758 (optimization and refactoring)

.github/workflows/test.yml
This eliminates the `build` action's warning on the Ubuntu builders.
=> chore: bump GH actions

nix/default.nix
jumping over the problematic (buggy?) 4.1.0 version, in the hope that some future `nixpkgs` will catch up someday
=> chore: forward bump to 5.0.1 of `js_of_ocaml`

test/run-drun/timer.mo
The updated schedule is
| seconds | reaction |
|----|-----|
| 1,0 | YEP! |
| 1,8  | DIM! |
| 3,0 | ROOK! |
| 3,6 | DIM! |
| 4,0 | BATT! |
| 5,0 | BATT! |
| 6,0 | BATT! |
whereas before the schedule was ambiguous
| seconds | reaction |
|----|-----|
| 1,0 | YEP! |
| 2,0  | DIM! |
| 3,0 | ROOK! |
| **4,0** | DIM! |
| **4,0** | BATT! |
| 5,0 | BATT! |
| 6,0 | BATT! |
=> chore: make `timer.mo` deterministic

src/codegen/compile.ml, src/exes/dune, src/idllib/lexer.mll, src/idllib/parser.mly, src/ir_interpreter/interpret_ir.ml, src/js/dune, src/lib/dune, src/lib/lib.ml, src/lib/lib.mli, src/linking/linkModule.ml, src/mo_frontend/source_lexer.mll, src/mo_frontend/typing.ml, src/mo_interpreter/interpret.ml, src/mo_values/prim.ml, src/mo_values/show.ml, src/mo_values/value.ml, src/wasm-exts/customModuleDecode.ml, src/wasm-exts/customModuleEncode.ml, test/test-moc.js, test/test-moc_interpreter.js
This PR makes the following changes:
- Adds `Lib.Utf8` with tail-recursive implementations for `encode` and `decode` ([based on `Wasm.Utf8`](https://github.com/WebAssembly/spec/blob/main/interpreter/binary/utf8.ml))
- Implements a new `is_valid` function in the `Lib.Utf8` module
- Replaces all existing usages of `Wasm.Utf8` with `Lib.Utf8`
- Adds relevant unit tests for the moc.js type checker and interpreter
TODO:
The original (non-tail-recursive) implementations remain in this PR for convenience during the code review. I'll remove these before merging. 
Fixes #3822.
=> fix: stack overflow in UTF-8 encode/decode for moc.js

default.nix
This PR swaps [uglify-js](https://www.npmjs.com/package/uglify-js) with [terser](https://www.npmjs.com/package/terser), a better-maintained JS minifier with more configuration options. By itself, this change has a negligible effect on minified file size, although we could potentially make further improvements by targeting newer JS output versions.
=> chore(js): replace `uglify-js` with `terser`

src/codegen/compile.ml, test/run/ok/array-bounds.wasm-run.ok
this has been in the back of my mind for a while: Originally, I intentionally used safe array access almost everywhere in the backend, even in places where the bounds should always be fine, so that bugs can be reported more efficiently. It seems that people have not found bugs related to that code, so we can drop the bounds check in compiler-generated loops over arrays (mostly in serialization/deserialization).
Turns out all array accesses that need to be bounds-checked go via the bignum index function anyways, so I moved the bounds check there.
=> Backend: Avoid pointless bounds checking array access

src/codegen/compile.ml, src/ir_def/check_ir.ml, src/ir_passes/const.ml
Variants with constant payloads should be constant and end up in the static heap. This will speed up all tree-like data structures that have unit-payload leaves (not to speak of allocation wins!). See https://github.com/dfinity/motoko-base/issues/543 for motivation.
For below program
``` Motoko
import P = "mo:⛔️";
type Tree = { #leaf; #node : (Tree, Tree) };
func leaf() : (Tree, (Nat, Nat)) = (#leaf, (5, 42));
P.debugPrint(debug_show leaf());
```
the function `leaf()` now looks like
``` wasm
(func $leaf (type 5) (param $clos i32)
i32.const 2097267
i32.const 2097279
global.set 18
global.set 17)
```
looks as expected. It also runs happily
```
$ wasmtime tree.wasm 
(#leaf, (5, 42))
```
=> perf: identify const variants

doc/md/language-manual.md
=> doc: fix definition of subtyping of object types in `language-manual.md`

src/prelude/internals.mo
There was a slightly buggy behaviour with setting the global timer from `@timer_helper`. We observed that for each one-off timer set there were two expirations happening. The reason is that we were computing the next expiration before the current batch of expired timers were expunged. This re-added the same time as before, and thus caused the second (in-vain) wakeup.
The fix is of course to compute the next global expiration _after_ the already expired nodes were expunged.
=> bugfix: check `@nextExpiration` after the changes are committed

src/codegen/compile.ml, src/ir_def/check_ir.ml, src/ir_passes/const.ml, test/run/ok/refuted-const-float.run.ok, test/run/ok/refuted-const-float.run.ret.ok, test/run/ok/refuted-const-float.tc.ok, test/run/ok/refuted-const-float.wasm-run.ok, test/run/ok/refuted-const-float.wasm-run.ret.ok, test/run/ok/refuted-const-option-null.run.ok, test/run/ok/refuted-const-option-null.run.ret.ok, test/run/ok/refuted-const-option-null.tc.ok, test/run/ok/refuted-const-option-null.wasm-run.ok, test/run/ok/refuted-const-option-null.wasm-run.ret.ok, test/run/ok/refuted-const-option.run.ok, test/run/ok/refuted-const-option.run.ret.ok, test/run/ok/refuted-const-option.tc.ok, test/run/ok/refuted-const-option.wasm-run.ok, test/run/ok/refuted-const-option.wasm-run.ret.ok, test/run/refuted-const-float.mo, test/run/refuted-const-option-null.mo, test/run/refuted-const-option.mo, test/run/refuted-const-variant.mo
This PR makes constant expressions fully matchable. We now also cover
- `LitP` and
- `OptP`
in the matching machinery. Thus there is no need to differentiate if the pattern is irrefutable.
Simplifies the logic quite a bit (as it should!)
-----------
TODO
=> compile-time match literals and options

src/prelude/prim.mo
- don't do repeated work
- early-return if there are no cycles to add
=> perf: improve `cyclesAdd`

doc/md/base/Trie.md, nix/drun.nix, src/docs/adoc.ml, src/docs/extract.ml, src/docs/html.ml, src/docs/plain.ml
Renders nested modules in the HTML, ADoc, and Markdown output formats. 
Fixes #1727.
=> feat(mo-doc): nested modules

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-hash.yml
solution by @crusso
Recent bump of `nix` to 2.15 broke our CI. Pinning 2.13.3, so that we can restore our manoeuvrability. It remains to be evaluated if it is only us or the general public that is affected.
See also #3932.
=> chore: specify `nix` version on CI by pinning v2.13.3

.github/workflows/update-hash.yml
standardise the way we get `nix`
This is a follow-up to #3933, as that broke this action due to invalid YAML.
=> chore: fix `update-hash`

nix/default.nix
=> chore: bump `rustc` stable to 1.66.1

nix/default.nix, nix/drun.nix
`cargo remove` is not needed anymore!
---------
This is moot now
Minor problem with `wasmtime` not adhering to convention:
> error: Use of `default_features` in `wasmtime` is unsupported, please switch to `default-features`
=> chore: bump `rustc` stable to v1.69

test/run.sh
Before:
```
Some tests failed:
recombine.mo recombine.mo recombine.mo recombine.mo recombine.mo recombine.mo recombine.mo recombine.mo
```
after:
```
Some tests failed:
recombine.mo
```
=> chore: show failed tests only once

src/codegen/instrList.ml, test/run/empty-if.mo, test/run/issue1356.mo
- `If` blocks with empty legs just `Drop`
- `If` blocks with empty `then` after comparison can invert the comparison and swap legs
The latter is not removing instructions, but cleans up the `.wat`, making it more idiomatic (and if we are lucky it saves cycles too).
``` diff wasm
local.get $buf
i32.load offset=4
local.get $buf
i32.load
-    i32.eq
+    i32.ne
if  ;; label = @1
-    else
i32.const 2098196
i32.const 30
call 31
unreachable
end
```
The former is needed so that we don't loop on the latter.
TODO:
=> perf: `If`-related peephole rules

src/codegen/compile.ml, src/ir_def/ir_utils.ml
Applies a shortcut when the inner pattern is a `WildP`. I also cover `()`, the prototypical non-binding irrefutable pattern.
Generally we now don't even make an attempt to enter into matching irrefutable patterns below options or tags when there are no bindings to fill.
This removes the unnecessary locals holding the scrutinees, since we don't have to project out for bindings or further pattern matching.
Normally the _push/drop_ peephole optimisation would _almost_ clean this up, but the local `tee` still remains.
Spotted in #3955.
Further optimisation could be to also allow:
- when the scrutinee is _singleton-typed_ with no bindings in the pattern (but that might be less interesting).
=> perf: improve codegen for `?_` and `#variant _` (and also `()`)

.github/workflows/comment-artifact-link.yml, .github/workflows/test.yml
When "build_artifacts" label is applied, CI builds the `moc` binary and uploads to artifact.
=> ci: add an artifact job

design/DFX-Interface.md, doc/md/about-this-guide.md, doc/md/compiler-ref.md, doc/md/language-manual.md, doc/md/motoko.md
Updates to the Motoko docs so it shows the correct naming for IC SDK
=> updates to Motoko mentions of the SDK and DFX

src/js/common.ml, src/lang_utils/error_codes/M0003.md, src/lang_utils/error_codes/M0149.md, src/lang_utils/error_codes/M0155.md, src/lang_utils/error_codes/M0156.md, src/lang_utils/error_codes/M0158.md, test/test-moc.js
- Sends more diagnostic information through `moc.js`
- Fixes various typos and formatting inconsistencies in the error code explanation files
=> feat: include error categories and codes in `moc.js` diagnostics

doc/md/examples/grammar.txt, src/mo_frontend/parser.mly
We currently allow
```
async ()
```
but not
```
async* ()
```
and just 
```
async* { ... }
```
Looks like a cut-n-paste error. Let's see if it passes CI.
=> bugfix: fix bug in grammar for `async*` expressions

default.nix
This is needed for the upcoming `nixpkgs` bump.
=> chore: bump `nodejs` to v18

default.nix, test/run-drun/ok/upgrades.ic-ref-run.ok
which has been deactivated in #3935 due to missing `ic0.is_controller` interface. (It was missing because we couldn't import the `ic-hs` changes.)
The change in the test case is due to https://github.com/dfinity/ic-hs/pull/179.
=> chore: reinstate the `ic-ref-run` test

Changelog.md, src/codegen/compile.ml, src/mo_values/prim.ml, src/prelude/prim.mo, test/run-drun/empty-actor.mo, test/run-drun/ok/upgrades.drun.ok, test/run-drun/ok/upgrades.ic-ref-run.ok, test/run-drun/upgrades/upgrade0.mo, test/run-drun/upgrades/upgrade1.mo
This PR adds support for the canister versioning feature of the IC, establishing the `canisterVersion` primitive.
A follow-up PR will amend the `create_canister` and `install_code` management canister calls (which we use to manage actor classes) with this information.
Retrieving the version history of canisters will be implemented from the `motoko-base` library.
=> feat: primitive for `ic0.canister_version`

.github/workflows/test.yml, default.nix, nix/sources.json
Recently imports of `drun` tend to fail building, because the storage is very constrained on Linux builders, and `nix` preloads all necessary binary artefacts for the whole build process. This meant that when the `drun` build started there were already `OCaml` and `ghc` as well as many instances of `llvm`, `clang` and `rustc` present.
This PR detects when `drun` is about to be built, does it in a frugal way, and also cleans up after itself.
If this method turns out to be effective in the middle term, we can adopt it for `rustc` and other bigger chunks too.
=> chore: perform scheduled builds of `drun` in a sparse artefact environment

rts/Makefile
the previous ones will be errors soon
=> chore: use non-deprecated flags when building RTS

default.nix
Does anybody know why these were needed in first place?
Anyway, if they are now needed for CI, we can remove them, right?
=> chore: remove unnecessary `ppx` dependencies

src/codegen/compile.ml, src/linking/linkModule.ml
No functionality changes. Also some cosmetics in `compile.ml`.
=> refactor: deduplicate two functions

release-files.nix
Here is a suggested PR to update the name of the release so they follow `$(uname -s)-$(uname -m)` convention. This would make it easier to fetch the releases from container build files like `Dockerfile`.
Hence: 
-  x86 Linux becomes `Linux-x86_64`
-  x86 Mac becomes `Darwin-x86_64`
In the future this would allow for: 
- M1/M2 Mac to become `Darwin-arm64`
- arm64 Linux to become `Linux-arm64`
Which would not have been possible under the current naming scheme which does not differentiate for the different macOS architecture (understandable as from my understanding there are no releases for M1/2 macOS yet).
_Note_: the legacy naming is still available. This will be discontinued when all downstream consumers have updated their procedures.
=> chore: change binary release artefact names

test/run-drun/ok/region0-stable-mem-grow-fail.drun-run.ok, test/run-drun/ok/stable-mem-grow-fail.drun-run.ok, test/run-drun/region0-stable-mem-grow-fail.mo, test/run-drun/stable-mem-grow-fail.mo
@luc-blaeser mentioned seeing  unexpected "stable memory out of bounds" failures.
I think the bug is due to region_grow only checking the page allocation against the logical maximum determented --max-stable-pages, which may be set higher than what is currently available on the replica. In particular, the region_grow implementation fails to check whether the call to ic0.grow actually succeeds and pretends it has, which then let's you read/write unallocated pages.
This test reproduces the error. 
It's actually fixed in https://github.com/dfinity/motoko/pull/4145
=> experiment: repro for bug in region.grow

rts/motoko-rts/src/region.rs, src/codegen/compile.ml, test/bench/ok/heap-32.drun-run-opt.ok, test/bench/ok/heap-32.drun-run.ok
Builds on #3768 
Simplifies regions code by using compiler/StableMem as underlying page allocator, avoiding error-prone duplication of state.
See follow-up PR #4145 that also avoids communication --max-stable-pages to the rts.
=> experiment: simplify regions 

.github/workflows/test.yml, rts/motoko-rts/src/ic0_stable.rs, rts/motoko-rts/src/region.rs, rts/motoko-rts/src/region0.rs, src/codegen/compile.ml, test/run-drun/ok/region0-stable-mem-grow-fail.drun-run.ok, test/run-drun/region0-stable-mem-custom-max.mo, test/run-drun/region0-stable-mem-max.mo
builds on #4143 (which builds on #3768)
--max-stable-pages is enforced in one place only, the low-level page allocator StableMem.
It now bounds the physical stable pages occupied by the user code, leaving the rest as reserve for stable variables.
This means some tests need to know if they are running with --stable-regions or not because the overheads are different.
=> experiment: refactor enforcement of --max-stable-pages

test/run-drun/ok/region0-overflow.drun-run.ok, test/run-drun/ok/region0-overflow.tc.ok, test/run-drun/region0-overflow.mo
A repro exposing the missing overflow check that we discussed (offset+len-1 can overflow).
=> bug: missing overflow check in regions.grow

doc/md/motoko.md
Change to align this page's title with the rest of the content
=> fix: title case of doc/md/motoko.md

test/drun-wrapper.sh
The regions PR #3768 bumped up drun-wrapper extra batches from 1 to 128, affecting the perf of perf/dao due to a longer running heartbeat. This restores the extra batches back to 1.
=> chore: revert drun-wrapper extra batches to 1 for perf measurement

.github/workflows/test.yml, src/codegen/compile.ml
My linux CI jobs have been failing due to lack of disk space.
I stumbled across this suggestion on the web
https://saturncloud.io/blog/github-action-ecr-optimizing-disk-space/#handling-or-maximizing-github-runner-out-of-disk-space-error
and it seems to help.
Maybe it's enough to just use the GH action https://github.com/jlumbroso/free-disk-space.
Ok, just this gives us back an extra 28GB of disk space. Hopefully that can keep us going for  a while more.
=> chore: modify CI to free linux disk-space before tests action

doc/md/about-this-guide.md, doc/md/motoko-introduction.md
This PR removes links to the page `/concepts/what-is-IC` in the Motoko docs, since this page has been deleted.
=> Update docs to remove links to deleted page

default.nix, nix/drun.nix, nix/sources.json, src/codegen/compile.ml, src/docs/.ocamlformat, src/languageServer/.ocamlformat, src/languageServer/definition.ml, test/browser-debug.js, test/lsp-int/Main.hs, test/lsp-int/lsp-int.cabal, test/random/Embedder.hs, test/random/qc-motoko.cabal, test/run.sh, wasm-profiler/src/instrumentation.rs
=> chore: bump `nixpkgs` to 23.11

src/exes/moc.ml
This PR includes doc comments from #4178 in the Candid files generated by dfx using the `--idl` compiler flag. 
Unblocks @tiagoicp's developer grant.
=> feat: add doc comments to Candid interfaces generated via `--idl` flag

Changelog.md, src/codegen/compile.ml, test/run-drun/ok/region-nat32-bug.drun-run.ok, test/run-drun/ok/region-nat32-bug.tc.ok, test/run-drun/region-nat32-bug.mo
bugfix: fix broken implementations of `Region.loadNat32`, `Region.storeNat32`, `Region.loadInt32`, `Region.storeInt32` (#4335). The operations were writing the 32-bit vanilla representation of the Motoko values, not the decoded values. 
Values previously stored with the broken 32-bit operations must be loaded with care.
If bit 0 is clear, the original value can be obtained by an arithmetic shift right by 1 bit.
If bit 0 is set, the value cannot be trusted and should be ignored (it encodes some transient address of a boxed value).
=> bugfix: fix Region.storeNat32/loadNat32 and Region.storeInt32/loadInt32 

Changelog.md, doc/md/compiler-ref.md
After a longer beta testing phase and some fine-tuning, we could officilalize the incremental garbage collector.
This would be next intermediate step before making the incremental GC the default GC in Motoko.
Some advice may be helpful to be given to developers, ideally also in a forum post, once we have declared the GC production ready.
The incremental GC is enabled by the moc flag `--incremental-gc` (#3837) and is designed to scale for large program heap sizes.
While resolving scalability issues with regard to the instruction limit of the GC work, it is now possible to hit other scalability limits:
- _Out of memory_: A program can run out of memory if it fills the entire memory space with live objects.
- _Upgrade limits_: When using stable variables, the current mechanism of …
=> Officializing the Incremental GC

doc/md/examples/grammar.txt, src/docs/extract.ml, src/docs/namespace.ml, src/lang_utils/error_codes.ml, src/lowering/desugar.ml, src/mo_def/arrange.ml, src/mo_def/compUnit.ml, src/mo_def/syntax.ml, src/mo_frontend/definedness.ml, src/mo_frontend/effect.ml, src/mo_frontend/parser.mly, src/mo_frontend/static.ml, src/mo_frontend/traversals.ml, src/mo_frontend/typing.ml, src/mo_interpreter/interpret.ml, test/fail/ok/issue-4323.tc.ok
Use the same procedure as with `ClassD`, viz. adding an optional type to `ObjBlockE` and checking for it after inferring the body's type.
=> extending `ObjBlockE` with optional conformity

src/lang_utils/error_codes.ml, src/mo_frontend/typing.ml, test/fail/actor-class-star.mo, test/fail/ok/actor-class-star.tc.ok, test/fail/ok/actor-class-star.tc.ret.ok
Since the parser already ensures that the return type of actor classes is `AsyncT`, the only way how this can be triggered is by having `T.Cmp`.
=> chore: remove the `FIXME` for duplicated `M0135`

doc/md/examples/StableMultiLog.mo
Fix the wrong calculation on the new pages needed to grow stable memory in the StableMultiLog example used in our documentation.
=> fix: wrong new_pages calculation in StableMultiLog

rts/cargo-vendor-tools/Cargo.toml, rts/motoko-rts-macros/Cargo.toml, rts/motoko-rts-tests/Cargo.toml, rts/motoko-rts/Cargo.toml, rts/motoko-rts/native/Cargo.toml, test/lsp-int/lsp-int.cabal, test/random/qc-motoko.cabal
Replaces `sdk@dfinity.org` with the recently introduced `team-motoko@dfinity.org`.
=> chore: update contact email

Building.md
Improve the release instructions to make the `mops` upload complete.
@ZenVoich the upload process did not check the `CHANGELOG.md` entry, but somewhere I read that it wouldn't let the upload proceed without a current one. What went wrong?
=> chore: add additional steps in `Building.md` for releasing `base` towards `mops`

src/mo_values/value.ml, test/repl/ok/pretty-val.stdout.ok, test/repl/ok/type-lub-repl.stdout.ok, test/repl/pretty-val.sh
builds on #4471 but:
* prints values at type Any/functions/computations as opaque `<any>`, `<func>`, `<async*>`
* elides dynamic fields of objects not visible from static type,
* prints all fields of objects only when  printing at sentinel type `T.Non`.
=> experiment: refined type-driven value printer

rts/motoko-rts/src/idl.rs, src/codegen/compile.ml, test/bench/candid-subtype-cost.mo, test/bench/ok/bignum.drun-run.ok, test/bench/ok/candid-subtype-cost.drun-run.ok, test/run-drun/max-stack-variant.mo, test/run-drun/max-stack.mo, test/run/idl.mo
Builds on #4193 
Builds the absolute global type table just once on entry to (candid) deserializer, not once on every call to idl_sub, avoiding 
repeated allocation.
The global type table data is stored in additional "Registers" (i.e. globals) to avoid passing them down the stack, but must be reset between GC runs as the type descriptors can be moved by GC.
Compare perf output
Master/EOP unpooled: [00285ba](https://github.com/dfinity/motoko/pull/4497/commits/00285ba840936466f545f458ac3fc30eb97e2ba3)
EOP unpooled/EOP pooled: [34937d9](https://github.com/dfinity/motoko/pull/4497/commits/34937d965f27e8b53a1aa6bf0019df847bd71472)
EOP pooled/this branch: [52c5f7f](https://github.com/dfinity/motoko/pull/4497/commits/52c5f7f3355ff577d8ff5d03285bd2e57a07a168)
TODO:
[ ] Should we remove the new …
=> experiment: remove regression in idl_sub 

.github/workflows/test.yml, .mergify.yml
This change has been made by @crusso from Mergify config editor.
=> ci(Mergify): configuration update to use macos-12 not macos-latest

.github/workflows/release.yml, .github/workflows/test.yml, .mergify.yml, doc/md/stable-regions.md, nix/sources.json
GH now uses M1 for macos-latest, not x86, which was breaking our CI. This PR specify that GH actions should use macos-12, the LKG for our CI.
PR https://github.com/dfinity/motoko/pull/4522 updated .mergify.yml to use macos-12 (not macos-latest), faking the macos-latest test results in order to pass CI checks and merge.
This PR update our GH actions to use macos-12 and to satisfy the .mergify.yml merged by https://github.com/dfinity/motoko/pull/4522.
Unfortunately, even though the macos-12 checks pass and I should be able to merge, some status check is hanging waiting for tests (macos-latest) to finish (which it never will). I believe, but cannot be sure, that this is due to some GH branch protection that I can't edit. So I've added macos-latest back to the test matrix, but skip the actual …
=> chore: downgrade to macos-12 for GH workflows

.github/workflows/test.yml
Our branch protection rules now require check `test (macos-12)`, not `test (macos-latest)`.
We build `test (macos-12)`, since `macos-latest`, since April 24, is now an M1 target, breaking our builds (`macos-12` is x86 and the previous default for `macos-latest`).
=> chore: remove GH no-longer required task `test (macos-latest)`

doc/md/reference/language-manual.md
Fixes broken rendering of pipe in tables (logical or, or-updated and expression piping).
(verified with make preview for docusaurus 2.x)
=> doc: use html to display | in tables

rts/motoko-rts-tests/src/gc.rs, rts/motoko-rts-tests/src/gc/compacting/mark_stack.rs, rts/motoko-rts-tests/src/gc/incremental/array_slicing.rs, rts/motoko-rts-tests/src/gc/incremental/partitioned_heap.rs, rts/motoko-rts/src/debug.rs, rts/motoko-rts/src/types.rs, rts/motoko-rts/src/visitor.rs, src/codegen/compile.ml, src/mo_values/prim.ml, src/prelude/internals.mo, src/prelude/prim.mo
builds on #4544 
Introduce two new tags:
`TAG_BLOB_A` : a blob representing an actor reference (distinct from a raw principal).
`TAG_ARRAY_S`:  a pair representing a shared function as an actor reference (TAG_BLOB_A) paired with a method name as a text blob (TAG_BLOB_T).
Adding these tags now, to distinguish from other values, will hopefully give us some leverage if we ever want to change their representation in the future (perhaps adding type descriptors to drive dynamic serialization, for example).
Requires some additional coercions primitives to convert from blobs to principals (missing from #4544) and actors to blobs, copying payload with a different tag.
TODO:
=> experiment: precise heap tags for actors and shared functions

src/codegen/compile.ml, src/mo_frontend/typing.ml, src/prelude/prim.mo, test/fail/ok/M0200.tc.ok, test/fail/ok/no-timer-canc.tc.ok, test/fail/ok/no-timer-set.tc.ok
Builds on #4580.
Moves M0200 error detection from compile.ml to typing.ml, using special #deprecation M0200  in Prim.ml (the same trick we use to selectively deprecate stable memory prims).
=> experiment: reimplement M0200 for #4580

rts/motoko-rts/src/memory/ic.rs
Refining the allocator’s memory reserve for better maintainability.
The current allocator is based on the assumption that the memory reserve is at least of a WASM page size (64 KB) to guard against overflows of the shadow call stack (used in Rust and in the compiler backend).
This assumption is always met, i.e. the RTS is already safe:
* In the incremental GC: The memory reserve is at least 256 MB. When the GC is inactive, the reserve is increased by additional 640 MB.
* In the classical GCs: The reserve is constantly 256 MB.
This change relaxes this assumption and directly guards the last page in the allocator, independent of the GC’s memory reserve. This is only to increase robustness for future changes, where different memory reserves may be configured, potentially even below a page …
=> Refine the Memory Reserve Handling in the Allocator

rts/motoko-rts-tests/src/main.rs, rts/motoko-rts-tests/src/stable_option.rs, rts/motoko-rts/src/gc/incremental.rs, rts/motoko-rts/src/gc/incremental/partitioned_heap.rs, rts/motoko-rts/src/gc/incremental/phases/evacuation_increment.rs, rts/motoko-rts/src/gc/incremental/phases/mark_increment.rs, rts/motoko-rts/src/gc/incremental/phases/update_increment.rs, rts/motoko-rts/src/lib.rs, rts/motoko-rts/src/stable_option.rs
Related to enhanced orthogonal persistence, see https://github.com/dfinity/motoko/pull/4193.
As the Rust-native `Option` type may change its implementation and memory representation in future Rust releases, the runtime system for enhanced orthogonal persistent should use a dedicated option type in the internal persistent state. This dedicated option type has a long-term fixed representation (in C-layout convention) and is used in the garbage collector state that is again part of the persistent metadata.
=> EOP: Using a Dedicated Stable Option Type in Persistent State

src/lang_utils/error_codes.ml, src/mo_frontend/stability.ml, src/mo_types/type.ml, test/cmp/ok/mut-x-x.cmp.ok, test/cmp/ok/neg-xyz-x.cmp.ok, test/cmp/ok/neg-xyz-y.cmp.ok, test/cmp/ok/old-new.cmp.ok, test/cmp/ok/x-mut-x.cmp.ok
This is used by `dfx` to check the upgrade compatibility with regard to the stable variables.
**Note**: With EOP, the Motoko RTS implements an atomic and authoritative upgrade compatibility check that cannot be bypassed. Hence, the `dfx` check only provides an additional help for the user. 
Enhanced orthogonal persistence offers more liberal rules for more flexible upgrades:
- Mutability of stable fields can be changed because they are never aliased.
- Stable fields can be dropped, however, with a warning of potential data loss. For this, we give up the transitivity property of upgrades.
**Note**: Upgrade transitivity means that an upgrade from a program `A` to `B` and then from `B` to `C` has the same effect as directly upgrading from `A` to `C`. Now, if `B` discards a field and `C` …
=> EOP: Relaxed Upgrade Compatibility Check

README.md
This one:
I sourced it from https://dfinity.frontify.com/d/pD7yZhsmpqos/motoko#/-/logo (just download the `.zip` and unpack)
=> chore: add Motoko logo to `README.md`

src/exes/moc.ml, src/lang_utils/diag.ml, src/lang_utils/source.ml, src/lang_utils/source.mli, src/mo_config/flags.ml
Add `--print-source-on-error` to print the source code for error messages.
=> feat: print source code on error

doc/md/writing-motoko/async-data.md, doc/md/writing-motoko/async-star.md
Documents the async*/await* feature, with (checked) examples.
=> doc: document async/await*

src/linking/linkModule.ml, test/ld/ok/representative.linked.wat.ok
Rust requires a table offset of at least 1 as the element index 0 is considered invalid and causes a debug null check to panic when called. On the other hand, `elem[0]` can be used by the Motoko backend code, as correct Rust-generated Wasm code does not call `elem[0]`.
This bug is independent of `wasm32` and `wasm64`.
This issue has been observed in https://github.com/dfinity/motoko/actions/runs/10703077671/job/29672766216?pr=4683 and happened only on Linux and only under `nix-build` (not `nix-shell`).
=> Fix: Start Wasm table for the RTS at offset >= 1

Building.md, Changelog.md, src/codegen/compile_classical.ml, src/codegen/compile_enhanced.ml, src/ir_def/arrange_ir.ml, src/ir_def/check_ir.ml, src/ir_def/construct.ml, src/ir_def/ir.ml, src/lowering/desugar.ml, src/prelude/prim.mo, test/fail/ok/no-timer-canc.tc.ok, test/fail/ok/no-timer-set.tc.ok, test/run-drun/basic-cycles.mo, test/run-drun/empty-actor-classical.mo, test/run-drun/ok/basic-cycles.tc.ok
This adds a new primitive `(prim "cyclesBurn")` and a `prim.mo` function `cyclesBurn : <system> Nat -> Nat`. It can be used to burn (some of the) canister's cycles programmatically using the system interface `ic0.cycles_burn128`.
=> feat: burning cycles programmatically

default.nix
As the test only runs in the interpreter, there is no need for distinguishing between EOP and classical persistence.
=> chore: skip redundant `repl` test on CI

doc/md/writing-motoko/intercanister-calls.md
Updates the documentation in response to [this forum post](https://forum.dfinity.org/t/ic-call-or-experimentalinternetcomputer-call/36900).
=> docs: add usage example for `ExperimentalInternetComputer.call()` on "Inter-canister calls" page

src/prelude/internals.mo
Since the observation of a `null` in the expiration array means there will be no more found, it is pointless to stay in the loop. I expect 1 expiration per callback in the frequent case.
=> perf: use less cycles in `@timer_helper`

.github/workflows/release.yml, .github/workflows/test.yml, .mergify.yml
See: https://github.com/actions/runner-images/issues/10721
=> chore: use `macos-13` as `macos-12` is deprecated

doc/md/examples/grammar.txt, src/gen-grammar/grammar.sed, src/lowering/desugar.ml, src/mo_def/syntax.ml, src/mo_frontend/parser.mly, src/mo_frontend/stability.ml, src/mo_frontend/stability.mli, src/mo_frontend/typing.ml, src/mo_frontend/typing.mli, src/mo_types/type.ml, src/mo_types/type.mli
builds on #4829 and #4812, addressing syntactic stable signatures.
A stable signature is now either a single interface of stable fields (as before) or (the new bit)  a dual interface recording the pre and post upgrade interface when performing migration.
The pre and post fields are implicitly identical for a singleton interface and provide for backwards compatibility and ordinary upgrades (sans explicit migration).
Stability compatibility now checks the post interface of old module is compatible with the pre-interface of the new module.
````
<stab_sig> ::=
<typ_dec>;* actor { <stab_field>;* }
<typ_dec>;* actor ( { <stab_field>;* },  <stab_field>;* } )
````
Done this way, there should be no need to modify dfx, which defers to moc for the compatibility check anyway.
=> experiment: support migration via extended stable interfaces

src/ir_def/construct.ml, src/ir_def/construct.mli, src/ir_passes/await.ml, src/lowering/desugar.ml, src/mo_frontend/typing.ml, src/mo_frontend/typing.mli, src/mo_types/type.ml, src/mo_types/type.mli, src/prelude/internals.mo, test/fail/ok/illegal-await.tc.ok
This fixes a disappearing timer situation described by Timo in https://dfinity.slack.com/archives/CPL67E7MX/p1736347600078339.
It turns out that under high message load the `async` timer servicing routine cannot be run. The fix is simple, check if the self-call succeeded (causes a `throw` already), and if not, set a very near global timer to retry ASAP (in the top-level `catch`).
TODO:
=> bugfix: check that timer servicing worked

Changelog.md, src/prelude/internals.mo, test/run-drun/call-raw.mo, test/run-drun/ok/call-raw.tc.ok
This was not possible before, as the attached cycles would go to the self-call, unutilised. Now we use the same logic as with actor class instantiation and delegate them in `@call_raw`.
=> feat: passing cycles to `call_raw`

doc/Makefile, doc/docusaurus/src/pages/index.js, doc/docusaurus/static/load_moc.ts
Add a new make target that builds a documentation preview outside of nix.
Might require installation of `make`, `node` and `npm` if not available.
```
cd doc
make doc
```
or
`make -C doc doc`
=> doc: `make doc` without requiring nix magic

Changelog.md, src/docs/extract.ml
Fixes #4901.
Unfortunately, we don't seem to have a test-suite for `mo-doc`, so hard to add tests at the moment.
=> bugfix: extend `mo-doc` to produce documentation for `actor` and `actor class` compilation units

src/mo_frontend/typing.ml, test/fail/ok/M0028.tc.ok, test/fail/ok/modexp1.tc.ok, test/fail/ok/pretty.tc.ok, test/fail/ok/suggest-long-ai.tc.ok, test/fail/ok/suggest-long.tc.ok, test/fail/ok/suggest-short-ai.tc.ok, test/fail/ok/suggest-short.tc.ok
Changes the `field * does not exist in type` error message to use the AST range of the field identifier rather than the parent expression. 
Mostly relevant for the Motoko VS Code extension, Motoko Playground, and ICP Ninja.
=> fix: improve error highlighting range for `M0072`

doc/md/reference/language-manual.md
Fixes what appears to be a typo in the BNF grammar for Motoko imports.
=> docs: fix grammar for imports

default.nix
Adds the `ocaml-lsp` dependency.
=> Add `ocaml-lsp` dependency to `default.nix`

test/bench/candid-subtype-cost.mo, test/bench/ok/candid-subtype-cost.drun-run.ok
See: dfinity/portal#5240.
I have also filed krpeacock/ic-management-canister#1.
=> chore: add `memory_metrics` to `canister_status`

nix/sources.json
We haven't done this for quite some time, but still stuck at 24.05 😔
---------------
to potentially avoid V8 bug that is
```
+TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
+
+Node.js v22.4.1
```
=> chore: bump `nixpkgs`

nix/default.nix, test/test-moc_interpreter.js
We used to build v5.0.1 ourselves, as there were correctness problems with v4.1.x. This reverts back to the supplied one that is bundled with OCaml 4.13.
------------
there is some fallout, though, as the `limit.mo` test won't let us to iterate up to 10000. I had to reduce it to the 7600 mark due to a stack overflow:
``` diff
>   {
result: {
+     error: {}
-     error: null
},
+   stderr: 'limit.mo:1.23-1.27: internal error, Stack overflow\n' +
+     '\n' +
+     'Last environment:\n' +
+     '@ManagementCanister = {}\n' +
+     '@add_cycles = <func>\n' +
```
I am trying to figure out where this started happening in #4969.
=> chore: use the stock `js_of_ocaml`

src/lang_utils/error_codes.ml, src/mo_frontend/typing.ml, test/fail/migration.mo, test/fail/ok/check-record.tc.ok, test/fail/ok/migration.tc.ok, test/repl/ok/pretty-val.stderr.ok, test/run-drun/ok/data-params.tc.ok, test/run-drun/ok/issue2317.tc.ok, test/run/object-extend.mo, test/run/ok/object-extend.tc.ok
This now warns when a user constructs a record with a field that will be dropped because the result is used as a supertype.
It cross-checks user-provided explicit fields (i.e. ignoring bases) and warns for those that don't appear in the expected type (in checking mode).
Resolves #4976.
TODOs:
- Do we want this for `object`s and `class`es too? (see #4981)
=> feat: detect lost fields in records (extensions)

nix/default.nix, nix/drun.nix
=> chore: bump `rustPlatform_moz_stable` (used for `drun`)

src/js/common.ml, src/js/moc_js.ml, src/pipeline/pipeline.ml, src/pipeline/pipeline.mli, test/test-moc.js
In order to improve the performance of the LSP server we need to be able to cache and pass cached the type checking context (`Scope.t`). It's helpful in two situations: 
* When the server initializes, it scans all files in the vscode workspace, and a library code (e.g. `mo:base`) is parsed and type-checked as many times as it's imported (transitively) in any other file. Caching fixes this by allowing dependency type information to be reused.
* Imagine that an IDE user is working on a file, so the content of the file is changed often while its dependencies are not. Scope caching then significantly reduces the compiler effort needed to get a new type information for the file.
**Changes:**
* `src/pipeline/`
* Add `load_progs_cached`/`chase_imports_cached` that are like …
=> LSP:  Implement a cache for typechecking (Serokell, Milestone-1)

nix/default.nix, src/exes/candid_tests.ml
this is in preparation for `rustc`-nightly bump and `nixpgks` 24.11 upgrade
The overlay can be zapped when `nixpkgs` gets bumped.
Needed a few CLI args fixes.
=> chore: supply `wasmtime` from `nixpkgs` 24.11

.github/workflows/test.yml
This reverts commit 4d5595ac1064a09c5ea3e6bbb74e2db97f8c4603, which was a critical ingredient for #5002 to pass, but the functionality needs to be restored.
=> chore: Revert "deactivate `performance delta` for now"

.github/workflows/test.yml, .github/workflows/update-hash.yml, default.nix, test/bench/ok/palindrome.drun-run.ok, test/bench/ok/region-mem.drun-run.ok, test/bench/ok/region0-mem.drun-run.ok, test/bench/ok/stable-mem.drun-run.ok
Looks like our local build environments are too diverse to single out one platform for local testing. So I went with CI-side updating of the numbers, creating commits.
This will require folks to do either a `git pull` at times or a `git pull --rebase` if you added commits in the meantime. Trying to push without that will be rejected. I hope that is acceptable!
=> chore: automatically push accepted `test/bench` numbers on `x86_64-linux`

src/dune, src/idllib/pipeline.ml, src/idllib/resolve_import.ml, src/idllib/resolve_import.mli, src/languageServer/declaration_index.ml
Just saw these run by when building fresh
In `src/` `make clean && make` should now compile without warnings.
I decided to ignore warning 70 (missing .mli files) during development, as we seem to generally not mandate interface files.
=> chore: fixes warnings in `src/`

rts/motoko-rts-tests/src/gc/enhanced.rs, rts/motoko-rts-tests/src/gc/incremental/roots.rs, rts/motoko-rts/src/gc/incremental/roots/enhanced.rs, rts/motoko-rts/src/persistence.rs, rts/motoko-rts/src/persistence/name_resolution.rs, rts/motoko-rts/src/persistence/stable_functions.rs, src/codegen/compile_enhanced.ml, test/run-drun/dropping-stable-functions.drun, test/run-drun/dropping-stable-functions/migration.mo, test/run-drun/dropping-stable-functions/version0.mo, test/run-drun/dropping-stable-functions/version1.mo, test/run-drun/dropping-stable-functions/version2.mo, test/run-drun/missing-stable-functions.drun, test/run-drun/missing-stable-functions/version0.mo, test/run-drun/missing-stable-functions/version1.mo, test/run-drun/ok/dropping-stable-functions.drun.ok, test/run-drun/ok/missing-stable-functions.drun.ok
Through table lookup for resolving RTS-internal name hash to the fully-qualified name.
Used to report missing stable functions or mismatching closure types.
=> Stable Functions: Display Function Names in RTS Errors

.github/workflows/test.yml, default.nix
This PR splits the CI testing pipeline between release and debug builds, adding more fine-grained control and parallelism for running the tests.
=> chore: support for splitting tests between `release` and `debug` builds

rts/motoko-rts/src/idl.rs
Just something I spotted while reading the Candid subtyping check in the RTS. This function doesn't return a pointer anymore, it updates the passed `buf` instead
=> docs: updates comment on parse_idl_header

emacs/motoko-ts-mode.el
The existing `motoko-model.el` in this repo is based on `swift-mode`, which is a bit sad.
With Emacs 29+ we finally got built-in tree-sitter support, so now it's relatively easy to get nice syntax highlighting and auto-indentation behaviour. Most of the _actual work_ was done by this grammar author: https://github.com/polychromatist/tree-sitter-motoko
This is pretty bare-bones, but I intend on adding a few rules here or there as I spot things that don't highlight or indent nicely.
Add this line to your config:
```lisp
(load "/path/to/motoko-ts-mode.el")
```
and run `treesit-install-language-grammar`, pass `motoko` as the grammar name and https://github.com/christoph-dfinity/tree-sitter-motoko as the grammar repo. The remaining prompts can stay as defaults.
Afterwards opening `.mo` files …
=> feat: defines a tree-sitter based Motoko mode for Emacs

nix/shell.nix
Not sure about `direnv`'s needs, though...
=> chore: add missing tools to get `make -C test` working again

test/drun-wrapper.sh, test/run-drun/check-app-subnet.drun, test/run-drun/check-app-subnet/check-app-subnet.mo, test/run-drun/check-system-subnet.drun, test/run-drun/check-system-subnet/check-system-subnet.mo, test/run-drun/ok/check-app-subnet.drun.ok, test/run-drun/ok/check-system-subnet.drun.ok, test/run.sh
`run-drun` tests can now run as an application subnet, which is important for certain kinds of tests where subnet types differ.
To run under this mode, one needs to add
```
```
in their `.drun` test file. The default is still running as a system subnet.
=> chore: allow `drun` to run as app subnet

emacs/motoko-ts-mode.el
Handles a lot more cases for indentation and syntax highlighting.
After updating you need to run `treesit-install-language-grammar` once more to pull in the new grammar.
I've been using this for a while now, and am pretty happy with my Motoko experience in Emacs.
=> feat: uses a new tree-sitter grammar for the Emacs mode

.github/workflows/release.yml, nix/release-files.nix
For some reason ripgrep missed these occurrences...
Fixes this CI failure: https://github.com/dfinity/motoko/actions/runs/14757948117/job/41431029555
=> fix: removes more `mo-ide` leftovers

.github/workflows/nightly-macos-test.yml, .github/workflows/test.yml
`MacOS` tests on `x86` are now run and the respective artifacts are built on a nightly CI job. See: #5119 . We can therefore remove them from running on every CI invocation, speeding up the process.
=> chore: remove `macos + x86` from CI runs

src/Makefile
A recent change to `src/Makefile` had the unintended effect of `make -C src` erroring out on harmless warnings, like `assert false; ...`, etc.
=> chore: relax `dune` profile for local compilation

.github/actions/test-blueprint/action.yml, .github/workflows/release.yml, .github/workflows/test.yml, Building.md, nix/rts.nix
This reverts commit 397b80a which enabled content-addressed derivations for the RTS.
Content-addressed derivations are causing caching issues where Nix rebuilds the RTS from scratch even when identical outputs exist in the cache. This significantly increases build times in CI and for developers.
References:
- https://discourse.nixos.org/t/solve-slow-man-cache-the-content-addressed-way-but-not-ca-derivation/58463
=> chore: revert .#rts flake content-addressed

.mergify.yml
Changed the author condition in the auto-approve rule from `dfinity-bot` to `pr-automation-bot-public` to reflect the current bot used for automation.
=> chore: update `author` for auto-approve rule in Mergify configuration

.mergify.yml
Changed the author condition in the auto-approve rule from `pr-automation-bot-public` to `app/pr-automation-bot-public` to align with the current bot naming convention.
=> chore: update author condition for auto-approve rule in Mergify configuration

Changelog.md, src/codegen/compile_classical.ml, src/codegen/compile_enhanced.ml, src/mo_values/prim.ml, src/prelude/prim.mo, test/fail/ok/no-timer-canc.tc.ok, test/fail/ok/no-timer-set.tc.ok, test/fail/ok/suggest-long-ai.tc.ok, test/fail/ok/suggest-short-ai.tc.ok, test/run/array-gen.mo
This gives me a nice 2-3% speedup on the Hamt benchmarks.
Claudio wasn't sure if we needed extra write barriers compared to the non-mutable version for EOP, so I'm adding Luc to the reviewers.
=> feat: adds a primitive `Array_tabulateVar` function

src/lowering/desugar.ml, src/mo_types/type.ml, src/prelude/internals.mo, src/prelude/prim.mo, test/fail/ok/stable-box1.tc.ok, test/fail/ok/stable-box1.tc.ret.ok, test/fail/ok/stable-box2.tc.ok, test/fail/ok/stable-box2.tc.ret.ok, test/fail/ok/stable-class-generics1.tc.ok, test/fail/ok/stable-class-generics1.tc.ret.ok, test/fail/ok/stable-class-generics2.tc.ok, test/fail/ok/stable-class-generics2.tc.ret.ok, test/fail/stable-box1.mo, test/fail/stable-box2.mo, test/fail/stable-class-generics1.mo, test/fail/stable-class-generics2.mo
Fixing https://github.com/dfinity/motoko/pull/5143
Essence of fix:
* Can only promote stable function type to flexible type, when there are no generic type parameters.
This is because:
* Stable functions imply stable type parameters
* Flexible functions imply flexible type parameters
* Promotion requires generic invariance on stability
=> Stable Functions: Minor Fix (Promoting Stable Functions with Generic Type Parameters)

doc/md/base/index.md, doc/md/core/index.md, src/docs/html.ml, src/docs/plain.ml
Makes it so we produce the desired documentation output from #5285
=> fix(mo-doc): rewords heading for package index

src/codegen/compile_enhanced.ml, src/exes/moc.ml, src/mo_config/flags.ml
Address the following mysterious js_of_ocaml warnings:
js_of_ocaml int are 32-bit and these constants exceed that (but do fit into 63-bit) Ocaml ints.
```
crusso@crusso-Virtual-Machine:~/motoko/src$ make moc.js
source_id/gen.sh
dune build --profile=release --profile=release _build/default/js/moc_js.bc.js
Warning: integer overflow: integer 0x29e8d60800 (180000000000) truncated to 0xe8d60800 (-388626432); the generated code might be incorrect.
Warning: integer overflow: integer 0x430e23400 (18000000000) truncated to 0x30e23400 (820130816); the generated code might be incorrect.
ls -al _build/default/js/moc_js.bc.js
-r--r--r-- 1 crusso crusso 2456599 Aug  7 16:12 _build/default/js/moc_js.bc.js
crusso@crusso-Virtual-Machine:~/motoko/src$ 
```
=> chore: fix warnings in moc_js

doc/md/12-base-core-migration.md
Miscellaneous improvements to the `base` -> `core` migration guide.
=> doc: migration guide tweaks

src/mo_frontend/typing.ml, test/fail/lambdas-core.mo
=> fix: Missing type note update (leaving `???` `Type.Pre`) in enhanced type inference path

doc/md/12-base-core-migration.md
Adds information for migrating from the `Heap`, `None`, `RBTree`, and `Trie` modules.
=> Update `core` migration guide

src/lowering/desugar.ml
Just a small refactor I noticed while working on something else.
The definition of `transform_unit` just above this function (just to make reviewing a little easier):
```ocaml
let transform_unit (u : S.comp_unit) : Ir.prog  =
let { imports; body; _ } = u.it in
let imports' = List.concat_map transform_import imports in
let body' = transform_unit_body body in
inject_decs imports' body', Ir.full_flavor()
```
=> refactor: remove code duplication in desugaring

flake.nix
Run `test-runner` tests as part of building the package instead of separate tests. Simplifies nix code.
=> fix: Fix `test-runner` tests

Changelog.md, doc/md/15-compiler-ref.md, src/exes/moc.ml, src/lang_utils/diag.ml, src/lang_utils/error_codes.ml, src/lang_utils/error_codes.mli, src/mo_config/flags.ml, test/fail/ok/warn-help.tc.ok, test/fail/ok/warnings-as-errors.tc.ok, test/fail/ok/warnings-as-errors.tc.ret.ok, test/fail/warn-help.mo, test/fail/warnings-as-errors.mo
- Adds `-E` moc flag to complement `-A` and `-W`, can be used to treat selected warnings as errors (set their lint level to error). Only warnings can be modified. Messages raised as `error` are left untouched. This is important note, because some warning codes are used as `error`. These instances won't be affected. Only when calling with `warn` can the configuration be used to change the severity of the message.
- Adds `--warn-help` flag that lists all configurable warnings with their current lint level and their brief description
=> feat: Warnings as Errors selectively

src/mo_frontend/typing.ml, test/fail/ok/implicit-import-hint-dot.tc.ok, test/run/contextual-dot.mo
Fixes #5544
The fix is a bit ugly, but it's very local in scope. I added a clarifying comment, but I'll keep thinking about it for a while to see if there's a more principled solution.
=> fix: fixes a bug with contextual dot and a tuple receiver

src/mo_frontend/typing.ml, test/fail/ok/implicit-import-hint-dot.tc.ok, test/run/contextual-dot.mo
This reverts commit 69f0aa8bf95271b49d808a9aa28a4615737e8b7c.
Causes regressions when interacting with functions accepting implicits.
=> Revert "fix: fixes a bug with contextual dot and a tuple receiver (#5547)"

.github/workflows/test.yml, .mergify.yml, Building.md, CI.md
It should be possible to instead use GitHub actions and the `gh` tool to
emulate the subset of functionality that we use Mergify for.
As communicated to the team:
> I have activated the “Enable auto-merge (squash)” button on PRs (with the PR description as the default commit message) and tested it myself successfully for #5533. Please start using it and report back if you find something odd. We plan to phase-out Mergify this month and I’ll prepare a PR to remove all mentions to it, as GH seems to provide the same functionality that we need.
TODO:
Out of an abundance of caution I'll do the remaining work on a follow-up PR.
=> chore: reduce the Mergify dependency
